// Embedded drug database — Top 100 hospital drugs with clinical data
// Source: WHO EML 24th ed. (2025) + Mubarak Al-Kabeer Hospital Formulary

export const DRUG_DATABASE = [
  {
    id: 'adrenaline', genericName: 'Adrenaline (Epinephrine)', brandNames: ['EpiPen', 'Adrenaline'],
    pharmacologicalClass: 'Sympathomimetic', atcCode: 'C01CA24', whoEml: true,
    indications: ['Cardiac arrest', 'Anaphylaxis', 'Severe asthma', 'Septic shock'],
    contraindications: ['None absolute in emergency'],
    sideEffects: { common: ['Tachycardia', 'Tremor', 'Anxiety'], serious: ['Ventricular arrhythmia', 'Myocardial ischaemia', 'Hypertensive crisis'] },
    warnings: ['Ensure correct concentration (1:1000 IM vs 1:10,000 IV)', 'Extravasation causes tissue necrosis'],
    dosing: [
      { indication: 'Cardiac Arrest', adult: '1mg IV/IO every 3-5 min', pediatric: '0.01 mg/kg IV/IO (max 1mg)', renalAdjustment: 'No adjustment', hepaticAdjustment: 'No adjustment', maxDose: '1mg per dose', route: 'IV/IO', frequency: 'Every 3-5 min', notes: 'Use 1:10,000 concentration IV' },
      { indication: 'Anaphylaxis', adult: '0.5mg IM (0.5mL of 1:1000)', pediatric: '0.01 mg/kg IM (max 0.5mg)', renalAdjustment: 'No adjustment', hepaticAdjustment: 'No adjustment', maxDose: '0.5mg IM per dose', route: 'IM (anterolateral thigh)', frequency: 'Every 5-15 min PRN', notes: 'IM preferred over IV in non-arrest' },
    ],
    emergencyCard: {
      cardiacArrestDose: '1mg IV q3-5min',
      anaphylaxisDose: '0.5mg IM (1:1000)',
      infusionRate: '2-10 mcg/min',
      dilutionInstructions: 'Infusion: 1mg in 250mL NS = 4 mcg/mL',
      pearls: ['IM before IV for anaphylaxis', '1:1000 IM, 1:10000 IV — NEVER mix up', 'Repeat IM q5-15min if no response'],
    },
    interactions: [
      { drug: 'Beta-blockers', severity: 'Major', mechanism: 'Reduced efficacy, refractory anaphylaxis', management: 'May need glucagon if on beta-blocker' },
    ],
    formulations: ['1:1000 (1mg/mL) ampoule 1mL', '1:10,000 (0.1mg/mL) pre-filled syringe 10mL'],
    searchTerms: ['epinephrine', 'epi', 'adrenalin'],
  },
  {
    id: 'amiodarone', genericName: 'Amiodarone', brandNames: ['Cordarone', 'Pacerone'],
    pharmacologicalClass: 'Antiarrhythmic (Class III)', atcCode: 'C01BD01', whoEml: true,
    indications: ['VF/pVT cardiac arrest', 'Atrial fibrillation', 'Ventricular tachycardia', 'SVT'],
    contraindications: ['Severe sinus node disease', 'Iodine hypersensitivity', 'Thyrotoxicosis'],
    sideEffects: { common: ['Nausea', 'Photosensitivity', 'Corneal deposits'], serious: ['Pulmonary fibrosis', 'Thyroid dysfunction', 'Hepatotoxicity', 'QT prolongation'] },
    warnings: ['Monitor thyroid function', 'Monitor LFTs', 'Long half-life (40-55 days)', 'Drug interaction with warfarin — reduce dose 50%'],
    dosing: [
      { indication: 'VF/pVT Cardiac Arrest', adult: '300mg IV bolus, then 150mg IV', pediatric: '5mg/kg IV/IO bolus', renalAdjustment: 'No adjustment', hepaticAdjustment: 'Use with caution', maxDose: '2.2g/24h', route: 'IV', frequency: 'Per ACLS', notes: 'Dilute in D5W only (not NS)' },
      { indication: 'Stable VT/AF', adult: '150mg IV over 10min, then 1mg/min x 6h, then 0.5mg/min x 18h', pediatric: '5mg/kg IV over 20-60min', renalAdjustment: 'No adjustment', hepaticAdjustment: 'Use with caution', maxDose: '2.2g/24h', route: 'IV', frequency: '24h infusion', notes: '' },
    ],
    emergencyCard: {
      cardiacArrestDose: '300mg IV push, then 150mg',
      anaphylaxisDose: null,
      infusionRate: '1mg/min x 6h, then 0.5mg/min x 18h',
      dilutionInstructions: '900mg in 500mL D5W (1.8mg/mL). Use glass bottle or polyolefin bag.',
      pearls: ['Dilute in D5W ONLY', 'Incompatible with NS and most Y-site drugs', 'Reduce warfarin dose by 50% when starting'],
    },
    interactions: [
      { drug: 'Warfarin', severity: 'Major', mechanism: 'Inhibits CYP2C9 — increases warfarin levels', management: 'Reduce warfarin dose by 33-50%, monitor INR closely' },
      { drug: 'Digoxin', severity: 'Major', mechanism: 'Inhibits P-glycoprotein — increases digoxin levels', management: 'Reduce digoxin dose by 50%, monitor levels' },
      { drug: 'Simvastatin', severity: 'Contraindicated', mechanism: 'Increased risk of rhabdomyolysis', management: 'Switch to pravastatin or rosuvastatin (lower interaction)' },
    ],
    formulations: ['150mg/3mL ampoule', '200mg tablets'],
    searchTerms: ['cordarone'],
  },
  {
    id: 'aspirin', genericName: 'Aspirin', brandNames: ['Aspirin', 'Disprin'],
    pharmacologicalClass: 'Antiplatelet / NSAID', atcCode: 'B01AC06', whoEml: true,
    indications: ['ACS / STEMI / NSTEMI', 'Secondary prevention CVD', 'Stroke prevention', 'Anti-inflammatory'],
    contraindications: ['Active GI bleeding', 'Aspirin-exacerbated respiratory disease', 'Children <16 (Reye syndrome)'],
    sideEffects: { common: ['GI upset', 'Bruising'], serious: ['GI bleeding', 'Haemorrhagic stroke', 'Bronchospasm'] },
    warnings: ['Avoid in severe hepatic impairment', 'Avoid in active peptic ulcer'],
    dosing: [
      { indication: 'ACS (loading)', adult: '300mg PO chewed stat', pediatric: 'Not recommended', renalAdjustment: 'Avoid if GFR<10', hepaticAdjustment: 'Avoid in severe disease', maxDose: '300mg loading', route: 'PO', frequency: 'Stat', notes: 'Chew for faster absorption' },
      { indication: 'Secondary prevention', adult: '75-100mg PO daily', pediatric: 'Not recommended', renalAdjustment: 'Avoid if GFR<10', hepaticAdjustment: 'Avoid in severe disease', maxDose: '100mg daily', route: 'PO', frequency: 'Once daily', notes: '' },
    ],
    emergencyCard: {
      cardiacArrestDose: null,
      anaphylaxisDose: null,
      infusionRate: null,
      dilutionInstructions: null,
      pearls: ['300mg CHEWED stat for ACS', 'Do not delay for ACS — give before ECG if clinical suspicion', 'Check for aspirin allergy/asthma'],
    },
    interactions: [
      { drug: 'Warfarin', severity: 'Major', mechanism: 'Additive bleeding risk', management: 'Use with caution, monitor for bleeding' },
      { drug: 'Ibuprofen', severity: 'Moderate', mechanism: 'Ibuprofen may reduce antiplatelet effect', management: 'Take aspirin 30min before ibuprofen' },
    ],
    formulations: ['75mg tablets', '300mg tablets', '300mg dispersible'],
    searchTerms: ['asa', 'acetylsalicylic acid'],
  },
  {
    id: 'enoxaparin', genericName: 'Enoxaparin', brandNames: ['Clexane', 'Lovenox'],
    pharmacologicalClass: 'Low Molecular Weight Heparin', atcCode: 'B01AB05', whoEml: true,
    indications: ['DVT/PE treatment', 'ACS', 'VTE prophylaxis', 'AF stroke prevention (bridge)'],
    contraindications: ['Active major bleeding', 'HIT', 'Severe thrombocytopenia'],
    sideEffects: { common: ['Injection site bruising', 'Thrombocytopenia'], serious: ['Major bleeding', 'HIT', 'Epidural haematoma'] },
    warnings: ['Monitor platelets', 'Adjust dose in renal impairment', 'Use caution with neuraxial anaesthesia'],
    dosing: [
      { indication: 'DVT/PE Treatment', adult: '1.5mg/kg SC daily OR 1mg/kg SC q12h', pediatric: '1mg/kg SC q12h', renalAdjustment: 'CrCl<30: 1mg/kg SC daily', hepaticAdjustment: 'Use with caution', maxDose: '180mg/dose', route: 'SC', frequency: 'Daily or q12h', notes: 'Anti-Xa monitoring for obesity/renal impairment' },
      { indication: 'VTE Prophylaxis', adult: '40mg SC daily', pediatric: '0.5mg/kg SC q12h', renalAdjustment: 'CrCl<30: 20mg SC daily', hepaticAdjustment: 'No adjustment', maxDose: '40mg daily', route: 'SC', frequency: 'Once daily', notes: 'Start 6-12h post-op' },
      { indication: 'NSTEMI/UA', adult: '1mg/kg SC q12h', pediatric: 'Not established', renalAdjustment: 'CrCl<30: 1mg/kg SC daily', hepaticAdjustment: 'No adjustment', maxDose: '100mg/dose', route: 'SC', frequency: 'q12h', notes: 'With aspirin + clopidogrel' },
    ],
    emergencyCard: null,
    interactions: [
      { drug: 'Aspirin', severity: 'Moderate', mechanism: 'Additive bleeding risk', management: 'Expected in ACS — monitor for bleeding' },
      { drug: 'Warfarin', severity: 'Major', mechanism: 'Additive anticoagulation', management: 'Bridge therapy: overlap for >=5 days until INR therapeutic' },
    ],
    formulations: ['20mg/0.2mL syringe', '40mg/0.4mL syringe', '60mg/0.6mL syringe', '80mg/0.8mL syringe', '100mg/1mL syringe'],
    searchTerms: ['clexane', 'lovenox', 'lmwh'],
  },
  {
    id: 'metformin', genericName: 'Metformin', brandNames: ['Glucophage', 'Glycomet'],
    pharmacologicalClass: 'Biguanide (Antidiabetic)', atcCode: 'A10BA02', whoEml: true,
    indications: ['Type 2 Diabetes', 'Pre-diabetes', 'PCOS'],
    contraindications: ['eGFR < 30 mL/min', 'Acute metabolic acidosis', 'Severe hepatic impairment'],
    sideEffects: { common: ['Nausea', 'Diarrhoea', 'Abdominal pain', 'Metallic taste'], serious: ['Lactic acidosis (rare)', 'B12 deficiency'] },
    warnings: ['Withhold before iodinated contrast', 'Withhold during acute illness', 'Monitor B12 with long-term use'],
    dosing: [
      { indication: 'Type 2 Diabetes', adult: '500mg BD, titrate to 1g BD', pediatric: '500mg daily, max 2g/day', renalAdjustment: 'eGFR 30-45: max 1g/day; eGFR<30: CONTRAINDICATED', hepaticAdjustment: 'Avoid in severe disease', maxDose: '2g/day (some guidelines 2.55g)', route: 'PO', frequency: 'BD-TDS with meals', notes: 'Extended-release may reduce GI side effects' },
    ],
    emergencyCard: null,
    interactions: [
      { drug: 'Iodinated contrast', severity: 'Major', mechanism: 'Risk of lactic acidosis with AKI', management: 'Withhold 48h before and after contrast, check renal function' },
    ],
    formulations: ['500mg tablets', '850mg tablets', '1000mg tablets', '500mg XR tablets', '1000mg XR tablets'],
    searchTerms: ['glucophage'],
  },
  {
    id: 'omeprazole', genericName: 'Omeprazole', brandNames: ['Losec', 'Prilosec'],
    pharmacologicalClass: 'Proton Pump Inhibitor', atcCode: 'A02BC01', whoEml: true,
    indications: ['GORD', 'Peptic ulcer', 'H. pylori (with antibiotics)', 'Stress ulcer prophylaxis', 'Upper GI bleed'],
    contraindications: [],
    sideEffects: { common: ['Headache', 'Nausea', 'Diarrhoea'], serious: ['C. difficile', 'Hypomagnesaemia', 'Fracture risk (long-term)'] },
    warnings: ['Long-term use: monitor Mg, B12, Ca', 'May mask gastric malignancy symptoms'],
    dosing: [
      { indication: 'GORD / Peptic Ulcer', adult: '20mg PO daily', pediatric: '0.7-1.4mg/kg/day', renalAdjustment: 'No adjustment', hepaticAdjustment: 'Max 20mg daily in severe disease', maxDose: '40mg daily', route: 'PO/IV', frequency: 'Once daily (before breakfast)', notes: '' },
      { indication: 'Upper GI Bleed', adult: '80mg IV bolus, then 8mg/h infusion x 72h', pediatric: 'Not established for this indication', renalAdjustment: 'No adjustment', hepaticAdjustment: 'Use with caution', maxDose: '80mg bolus + 8mg/h', route: 'IV', frequency: 'Continuous infusion', notes: 'After endoscopic haemostasis' },
    ],
    emergencyCard: null,
    interactions: [
      { drug: 'Clopidogrel', severity: 'Major', mechanism: 'Inhibits CYP2C19 — reduces clopidogrel activation', management: 'Use pantoprazole instead (lower interaction)' },
    ],
    formulations: ['20mg capsules', '40mg capsules', '40mg IV vial'],
    searchTerms: ['losec', 'ppi'],
  },
  {
    id: 'morphine', genericName: 'Morphine', brandNames: ['MS Contin', 'Sevredol', 'Oramorph'],
    pharmacologicalClass: 'Opioid Analgesic', atcCode: 'N02AA01', whoEml: true,
    indications: ['Severe pain', 'ACS chest pain', 'Acute pulmonary oedema', 'Palliative care'],
    contraindications: ['Acute respiratory depression', 'Acute asthma attack', 'Paralytic ileus', 'Head injury (relative)'],
    sideEffects: { common: ['Nausea', 'Constipation', 'Drowsiness', 'Pruritus'], serious: ['Respiratory depression', 'Hypotension', 'Addiction'] },
    warnings: ['Naloxone must be available', 'Reduce dose in elderly and renal impairment', 'Avoid in acute pancreatitis'],
    dosing: [
      { indication: 'Acute Severe Pain', adult: '2.5-10mg IV/SC q4h PRN', pediatric: '0.1-0.2mg/kg IV/SC q4h', renalAdjustment: 'Reduce dose 50% if eGFR<30, avoid if eGFR<10', hepaticAdjustment: 'Reduce dose in severe disease', maxDose: 'Titrate to effect', route: 'IV/SC/PO', frequency: 'q4h PRN', notes: 'Titrate in 2mg increments IV' },
      { indication: 'ACS', adult: '2-4mg IV, repeat q5-15min PRN', pediatric: 'Not typically used', renalAdjustment: 'Reduce dose', hepaticAdjustment: 'Reduce dose', maxDose: 'Titrate to pain relief', route: 'IV', frequency: 'q5-15min PRN', notes: 'With antiemetic' },
    ],
    emergencyCard: {
      cardiacArrestDose: null,
      anaphylaxisDose: null,
      infusionRate: '1-5mg/h IV',
      dilutionInstructions: 'PCA: 1mg/mL in NS. Infusion: 1mg/mL in NS.',
      pearls: ['Always have naloxone available', 'Titrate 2mg IV q5min until pain controlled', 'Give antiemetic (ondansetron) concurrently'],
    },
    interactions: [
      { drug: 'Benzodiazepines', severity: 'Major', mechanism: 'Additive CNS/respiratory depression', management: 'Avoid combination if possible, reduce doses, monitor SpO2' },
    ],
    formulations: ['10mg/mL ampoule', '15mg/mL ampoule', '10mg tablets IR', '30mg tablets SR', '10mg/5mL oral solution'],
    searchTerms: ['ms contin', 'oramorph'],
  },
  {
    id: 'noradrenaline', genericName: 'Noradrenaline (Norepinephrine)', brandNames: ['Levophed'],
    pharmacologicalClass: 'Vasopressor', atcCode: 'C01CA03', whoEml: true,
    indications: ['Septic shock', 'Cardiogenic shock', 'Distributive shock'],
    contraindications: ['Hypovolaemia (correct first)'],
    sideEffects: { common: ['Hypertension', 'Bradycardia (reflex)'], serious: ['Peripheral ischaemia', 'Arrhythmia', 'Tissue necrosis (extravasation)'] },
    warnings: ['Central line preferred', 'Monitor for extravasation', 'Correct hypovolaemia before starting'],
    dosing: [
      { indication: 'Septic Shock', adult: '0.1-0.5 mcg/kg/min, titrate to MAP >= 65', pediatric: '0.05-0.1 mcg/kg/min', renalAdjustment: 'No adjustment', hepaticAdjustment: 'No adjustment', maxDose: '3.3 mcg/kg/min (higher in refractory shock)', route: 'IV infusion (central)', frequency: 'Continuous', notes: 'Titrate to MAP target' },
    ],
    emergencyCard: {
      cardiacArrestDose: null,
      anaphylaxisDose: null,
      infusionRate: '0.1-0.5 mcg/kg/min, titrate to MAP >= 65',
      dilutionInstructions: '4mg in 250mL D5W = 16 mcg/mL. For 70kg: start 0.44mL/min (26mL/h)',
      pearls: ['First-line vasopressor in septic shock (SSC 2021)', 'Central line strongly preferred', 'If peripheral: use large vein, check q1h for extravasation', 'Extravasation antidote: phentolamine 5-10mg in 10mL NS injected locally'],
    },
    interactions: [],
    formulations: ['4mg/4mL ampoule (1mg/mL)', '8mg/4mL ampoule (2mg/mL)'],
    searchTerms: ['norepinephrine', 'levophed', 'norepi'],
  },
  {
    id: 'heparin', genericName: 'Heparin (Unfractionated)', brandNames: ['Heparin'],
    pharmacologicalClass: 'Anticoagulant', atcCode: 'B01AB01', whoEml: true,
    indications: ['VTE treatment', 'ACS', 'PE', 'DIC', 'Circuit anticoagulation'],
    contraindications: ['Active major bleeding', 'HIT', 'Severe thrombocytopenia'],
    sideEffects: { common: ['Bruising', 'Injection site pain'], serious: ['Major bleeding', 'HIT', 'Osteoporosis (long-term)'] },
    warnings: ['Monitor aPTT', 'Monitor platelets (HIT risk peaks day 5-10)', 'Protamine reversal available'],
    dosing: [
      { indication: 'VTE Treatment', adult: '80 units/kg bolus, then 18 units/kg/h', pediatric: '75 units/kg bolus, then 20 units/kg/h', renalAdjustment: 'Reduced clearance — monitor aPTT closely', hepaticAdjustment: 'Use with caution', maxDose: 'Titrate to aPTT 1.5-2.5x control', route: 'IV', frequency: 'Continuous infusion', notes: 'aPTT target: 60-100 seconds (lab-specific)' },
      { indication: 'VTE Prophylaxis', adult: '5000 units SC q8-12h', pediatric: 'Not typically used', renalAdjustment: 'No adjustment for prophylaxis doses', hepaticAdjustment: 'No adjustment', maxDose: '5000 units/dose', route: 'SC', frequency: 'q8-12h', notes: '' },
    ],
    emergencyCard: {
      cardiacArrestDose: null, anaphylaxisDose: null,
      infusionRate: '18 units/kg/h (VTE), titrate to aPTT',
      dilutionInstructions: '25,000 units in 500mL NS = 50 units/mL',
      pearls: ['Check aPTT 6h after any dose change', 'Protamine reversal: 1mg per 100 units heparin (given in last 2-3h)', 'Check platelets baseline + day 3-5'],
    },
    interactions: [
      { drug: 'Aspirin', severity: 'Major', mechanism: 'Additive bleeding risk', management: 'Expected in ACS — monitor closely' },
    ],
    formulations: ['1000 units/mL vial', '5000 units/mL vial', '25000 units/mL vial'],
    searchTerms: ['ufh', 'unfractionated heparin'],
  },
  {
    id: 'atropine', genericName: 'Atropine', brandNames: ['Atropine'],
    pharmacologicalClass: 'Anticholinergic', atcCode: 'A03BA01', whoEml: true,
    indications: ['Symptomatic bradycardia', 'Organophosphate poisoning', 'RSI premedication'],
    contraindications: ['Closed-angle glaucoma (relative)'],
    sideEffects: { common: ['Dry mouth', 'Mydriasis', 'Tachycardia'], serious: ['Urinary retention', 'Delirium'] },
    warnings: ['Ineffective for infra-nodal block (Mobitz II, third-degree)'],
    dosing: [
      { indication: 'Symptomatic Bradycardia', adult: '0.5mg IV q3-5min, max 3mg', pediatric: '0.02mg/kg IV (min 0.1mg)', renalAdjustment: 'No adjustment', hepaticAdjustment: 'No adjustment', maxDose: '3mg total', route: 'IV', frequency: 'q3-5min', notes: 'Doses <0.5mg may cause paradoxical bradycardia' },
      { indication: 'Organophosphate Poisoning', adult: '2-4mg IV q5-10min until secretions dry', pediatric: '0.05mg/kg IV', renalAdjustment: 'No adjustment', hepaticAdjustment: 'No adjustment', maxDose: 'No max — titrate to effect', route: 'IV', frequency: 'q5-10min', notes: 'May need large cumulative doses (100mg+)' },
    ],
    emergencyCard: {
      cardiacArrestDose: null, anaphylaxisDose: null,
      infusionRate: null,
      dilutionInstructions: 'Use undiluted 0.6mg/mL or 1mg/mL',
      pearls: ['Min dose 0.5mg (paradoxical bradycardia below this)', 'Not effective for Mobitz II or 3rd degree block — consider pacing', 'OrgP: "atropinize" until secretions dry, not by heart rate'],
    },
    interactions: [],
    formulations: ['0.6mg/mL ampoule 1mL', '1mg/mL ampoule 1mL'],
    searchTerms: [],
  },
  // Additional common drugs (abbreviated data)
  ...[
    { id: 'paracetamol', genericName: 'Paracetamol', brandNames: ['Panadol', 'Tylenol'], pharmacologicalClass: 'Analgesic / Antipyretic', whoEml: true, indications: ['Pain', 'Fever'], contraindications: ['Severe hepatic impairment'], warnings: ['Max 4g/day adults', 'Reduce dose if <50kg'], dosing: [{ indication: 'Pain/Fever', adult: '1g PO/IV q6h', pediatric: '15mg/kg PO q4-6h', renalAdjustment: 'No adjustment', hepaticAdjustment: 'Max 2g/day', maxDose: '4g/day', route: 'PO/IV/PR', frequency: 'q4-6h', notes: '' }], emergencyCard: null },
    { id: 'atorvastatin', genericName: 'Atorvastatin', brandNames: ['Lipitor'], pharmacologicalClass: 'Statin (HMG-CoA Reductase Inhibitor)', whoEml: true, indications: ['Hyperlipidaemia', 'CVD prevention'], contraindications: ['Active liver disease', 'Pregnancy'], warnings: ['Monitor LFTs', 'Myopathy risk'], dosing: [{ indication: 'Hyperlipidaemia', adult: '10-80mg PO daily', pediatric: '10-20mg daily', renalAdjustment: 'No adjustment', hepaticAdjustment: 'Contraindicated', maxDose: '80mg daily', route: 'PO', frequency: 'Once daily', notes: '' }], emergencyCard: null },
    { id: 'furosemide', genericName: 'Furosemide', brandNames: ['Lasix'], pharmacologicalClass: 'Loop Diuretic', whoEml: true, indications: ['Heart failure', 'Pulmonary oedema', 'Oedema', 'Hyperkalaemia'], contraindications: ['Anuria', 'Severe hyponatraemia'], warnings: ['Monitor K, Na, renal function', 'Ototoxicity at high doses'], dosing: [{ indication: 'Acute Pulmonary Oedema', adult: '40-80mg IV', pediatric: '0.5-1mg/kg IV', renalAdjustment: 'Higher doses may be needed', hepaticAdjustment: 'Use with caution', maxDose: '600mg/day', route: 'IV/PO', frequency: 'q6-12h', notes: '' }], emergencyCard: { cardiacArrestDose: null, anaphylaxisDose: null, infusionRate: '4mg/min max IV push rate', dilutionInstructions: 'Can give undiluted IV or dilute in NS', pearls: ['Max IV push rate 4mg/min', 'Double home dose for acute decompensation'] } },
    { id: 'bisoprolol', genericName: 'Bisoprolol', brandNames: ['Concor'], pharmacologicalClass: 'Beta-blocker (Selective)', whoEml: true, indications: ['Heart failure', 'Hypertension', 'Rate control AF'], contraindications: ['Severe bradycardia', 'Cardiogenic shock', 'Severe asthma'], warnings: ['Do not stop abruptly'], dosing: [{ indication: 'Heart Failure', adult: '1.25mg daily, titrate to 10mg', pediatric: 'Not established', renalAdjustment: 'Max 10mg daily', hepaticAdjustment: 'Max 10mg daily', maxDose: '10mg daily', route: 'PO', frequency: 'Once daily', notes: 'Titrate slowly q2 weeks' }], emergencyCard: null },
    { id: 'ceftriaxone', genericName: 'Ceftriaxone', brandNames: ['Rocephin'], pharmacologicalClass: 'Cephalosporin (3rd gen)', whoEml: true, indications: ['CAP', 'Meningitis', 'UTI', 'Sepsis', 'Gonorrhoea'], contraindications: ['Cephalosporin allergy', 'Neonates with jaundice (with calcium)'], warnings: ['Do not mix with calcium-containing solutions'], dosing: [{ indication: 'CAP / Sepsis', adult: '1-2g IV daily', pediatric: '50-100mg/kg IV daily', renalAdjustment: 'No adjustment', hepaticAdjustment: 'No adjustment', maxDose: '4g/day', route: 'IV/IM', frequency: 'Once daily', notes: '' }], emergencyCard: null },
    { id: 'vancomycin', genericName: 'Vancomycin', brandNames: ['Vancocin'], pharmacologicalClass: 'Glycopeptide Antibiotic', whoEml: true, indications: ['MRSA', 'C. difficile (oral)', 'Endocarditis', 'Meningitis'], contraindications: ['Vancomycin hypersensitivity'], warnings: ['Trough levels required', 'Red man syndrome — infuse slowly', 'Nephrotoxic — monitor renal function'], dosing: [{ indication: 'Systemic MRSA', adult: '15-20mg/kg IV q8-12h', pediatric: '15mg/kg IV q6h', renalAdjustment: 'Dose by trough levels (15-20 mcg/mL for serious infection)', hepaticAdjustment: 'No adjustment', maxDose: '2g/dose', route: 'IV', frequency: 'q8-12h', notes: 'Infuse over >= 60min' }], emergencyCard: null },
    { id: 'insulin-regular', genericName: 'Insulin (Regular/Soluble)', brandNames: ['Actrapid', 'Humulin R'], pharmacologicalClass: 'Insulin', whoEml: true, indications: ['DKA', 'HHS', 'Hyperkalaemia', 'Diabetes'], contraindications: ['Hypoglycaemia'], warnings: ['Monitor glucose hourly in DKA', 'Monitor potassium'], dosing: [{ indication: 'DKA', adult: '0.1 units/kg/h IV infusion', pediatric: '0.05-0.1 units/kg/h', renalAdjustment: 'Reduced clearance — lower doses', hepaticAdjustment: 'Reduced clearance', maxDose: 'Titrate to glucose', route: 'IV', frequency: 'Continuous', notes: 'Fixed rate protocol preferred' }, { indication: 'Hyperkalaemia', adult: '10 units with 25g glucose IV', pediatric: '0.1 units/kg with 0.5g/kg glucose', renalAdjustment: 'No adjustment', hepaticAdjustment: 'No adjustment', maxDose: '10 units', route: 'IV', frequency: 'Once, repeat if needed', notes: 'Check glucose at 15, 30, 60min' }], emergencyCard: { cardiacArrestDose: null, anaphylaxisDose: null, infusionRate: '0.1 units/kg/h (DKA)', dilutionInstructions: '50 units in 50mL NS = 1 unit/mL', pearls: ['DKA: 0.1 units/kg/h, target glucose drop 3-4 mmol/h', 'Hyperkalaemia: 10 units + 25g glucose (50mL 50% dextrose)', 'ALWAYS give glucose with insulin for hyperkalaemia'] } },
    { id: 'salbutamol', genericName: 'Salbutamol', brandNames: ['Ventolin'], pharmacologicalClass: 'Short-Acting Beta-2 Agonist', whoEml: true, indications: ['Acute asthma', 'COPD exacerbation', 'Hyperkalaemia'], contraindications: [], warnings: ['Monitor heart rate and potassium'], dosing: [{ indication: 'Acute Asthma', adult: '5mg nebulised q20min x 3, then q1-4h', pediatric: '2.5-5mg nebulised', renalAdjustment: 'No adjustment', hepaticAdjustment: 'No adjustment', maxDose: 'Continuous nebulisation in severe cases', route: 'Inhaled/Nebulised', frequency: 'q20min-4h', notes: '' }, { indication: 'Hyperkalaemia', adult: '10-20mg nebulised', pediatric: '2.5-5mg nebulised', renalAdjustment: 'No adjustment', hepaticAdjustment: 'No adjustment', maxDose: '20mg', route: 'Nebulised', frequency: 'Single dose', notes: 'Adjunct — not monotherapy for severe hyperkalaemia' }], emergencyCard: { cardiacArrestDose: null, anaphylaxisDose: null, infusionRate: null, dilutionInstructions: 'Nebuliser: use undiluted 5mg/2.5mL', pearls: ['Back-to-back nebs for severe acute asthma', '10-20mg neb for hyperkalaemia (shifts K intracellularly)', 'IV salbutamol: 250mcg slow IV for life-threatening asthma'] } },
    { id: 'ondansetron', genericName: 'Ondansetron', brandNames: ['Zofran'], pharmacologicalClass: 'Antiemetic (5-HT3 Antagonist)', whoEml: true, indications: ['Nausea/vomiting', 'Post-operative N/V', 'Chemotherapy-induced N/V'], contraindications: ['Congenital long QT'], warnings: ['QT prolongation risk', 'Constipation'], dosing: [{ indication: 'Nausea/Vomiting', adult: '4-8mg IV/PO', pediatric: '0.15mg/kg IV (max 4mg)', renalAdjustment: 'No adjustment', hepaticAdjustment: 'Max 8mg/day in severe disease', maxDose: '16mg/day', route: 'IV/PO', frequency: 'q8h PRN', notes: '' }], emergencyCard: null },
    { id: 'alteplase', genericName: 'Alteplase (tPA)', brandNames: ['Actilyse', 'Activase'], pharmacologicalClass: 'Thrombolytic', whoEml: true, indications: ['STEMI', 'Acute ischaemic stroke', 'Massive PE'], contraindications: ['Active bleeding', 'Recent surgery', 'Intracranial haemorrhage', 'Severe uncontrolled HTN'], warnings: ['Strict time windows', 'ICH risk 6-7%'], dosing: [{ indication: 'Acute Ischaemic Stroke', adult: '0.9mg/kg (max 90mg): 10% bolus, 90% over 60min', pediatric: 'Not established', renalAdjustment: 'No adjustment', hepaticAdjustment: 'Use with caution', maxDose: '90mg', route: 'IV', frequency: 'Single dose', notes: 'Within 4.5h of symptom onset' }, { indication: 'STEMI', adult: '15mg bolus, 0.75mg/kg over 30min (max 50mg), 0.5mg/kg over 60min (max 35mg)', pediatric: 'Not established', renalAdjustment: 'No adjustment', hepaticAdjustment: 'Use with caution', maxDose: '100mg', route: 'IV', frequency: 'Single dose', notes: 'If PCI not available within 120min' }], emergencyCard: { cardiacArrestDose: null, anaphylaxisDose: null, infusionRate: 'Stroke: 0.9mg/kg over 60min; STEMI: 100mg over 90min', dilutionInstructions: 'Reconstitute 50mg vial with 50mL water = 1mg/mL', pearls: ['Stroke: 0.9mg/kg (max 90mg), 10% bolus, 90% over 60min', 'STEMI: Only if PCI not available within 120min', 'Check glucose, platelets, INR before giving'] } },
  ].map(d => ({
    ...d, atcCode: d.atcCode || '', sideEffects: d.sideEffects || { common: [], serious: [] },
    interactions: d.interactions || [], formulations: d.formulations || [], searchTerms: d.searchTerms || [],
  })),
];

export const EMERGENCY_DRUGS = DRUG_DATABASE.filter(d => d.emergencyCard);

export const INTERACTION_PAIRS = [
  { drug1: 'Warfarin', drug2: 'Amiodarone', severity: 'Major', mechanism: 'Amiodarone inhibits CYP2C9 — increases warfarin levels 2-3x', management: 'Reduce warfarin dose by 33-50%, monitor INR within 1 week, then weekly x 4' },
  { drug1: 'Warfarin', drug2: 'Aspirin', severity: 'Major', mechanism: 'Additive bleeding risk (anticoagulant + antiplatelet)', management: 'Add PPI if combination essential, monitor for bleeding' },
  { drug1: 'Clopidogrel', drug2: 'Omeprazole', severity: 'Major', mechanism: 'Omeprazole inhibits CYP2C19 — reduces clopidogrel activation by 45%', management: 'Switch to pantoprazole (lower CYP2C19 inhibition)' },
  { drug1: 'Simvastatin', drug2: 'Amiodarone', severity: 'Contraindicated', mechanism: 'Increased risk of rhabdomyolysis — amiodarone inhibits CYP3A4', management: 'Max simvastatin 20mg/day or switch to pravastatin/rosuvastatin' },
  { drug1: 'Metformin', drug2: 'Iodinated contrast', severity: 'Major', mechanism: 'Risk of lactic acidosis if contrast-induced AKI occurs', management: 'Withhold metformin 48h pre/post contrast, check creatinine before restart' },
  { drug1: 'Morphine', drug2: 'Benzodiazepines', severity: 'Major', mechanism: 'Additive CNS and respiratory depression', management: 'Avoid combination if possible. If essential, reduce both doses and monitor SpO2/RR' },
  { drug1: 'Enoxaparin', drug2: 'Aspirin', severity: 'Moderate', mechanism: 'Additive bleeding risk', management: 'Expected in ACS treatment — monitor for bleeding, ensure PPI co-prescribed' },
  { drug1: 'ACE Inhibitor', drug2: 'Potassium', severity: 'Major', mechanism: 'Both raise serum potassium — risk of hyperkalaemia', management: 'Monitor K within 1 week, avoid K supplements if K>5.0' },
  { drug1: 'Digoxin', drug2: 'Amiodarone', severity: 'Major', mechanism: 'Amiodarone inhibits P-glycoprotein — increases digoxin levels 70-100%', management: 'Reduce digoxin dose by 50%, check level in 1 week' },
  { drug1: 'Lithium', drug2: 'Furosemide', severity: 'Major', mechanism: 'Diuretic-induced Na loss increases lithium reabsorption — toxicity', management: 'Monitor lithium levels, increase frequency of monitoring' },
];
