// Emergency Protocol Decision Trees
// Source: AHA 2025, ERC 2021, ATLS 10th ed.

export const PROTOCOLS = [
  {
    id: 'acls-vfpvt', name: 'Adult Cardiac Arrest — VF/pVT', category: 'ACLS',
    description: 'Ventricular fibrillation / pulseless ventricular tachycardia',
    steps: [
      { title: 'Start CPR', description: 'High-quality CPR: rate 100-120/min, depth 5-6cm, full recoil. Minimize interruptions.', timer: 120, timerLabel: 'CPR Timer (2 min)' },
      { title: 'Attach Defibrillator', description: 'Apply pads. Analyze rhythm.', options: [{ label: 'VF / pulseless VT', nextStep: 2, color: 'red' }, { label: 'Asystole / PEA', nextStep: 10 }, { label: 'ROSC', nextStep: 11 }] },
      { title: 'Defibrillate', description: 'Biphasic: 120-200J (or device max). Monophasic: 360J.', warning: 'Clear patient before shock. Resume CPR immediately after shock.' },
      { title: 'Resume CPR — 2 minutes', description: 'High-quality CPR for 2 minutes after shock.', timer: 120, timerLabel: 'CPR Timer (2 min)', medication: { drug: 'Adrenaline', dose: '1mg IV/IO', route: 'Give after 2nd shock' } },
      { title: 'Rhythm Check', description: 'Pause CPR briefly. Check rhythm.', options: [{ label: 'Still VF/pVT — Shock again', nextStep: 5, color: 'red' }, { label: 'Asystole / PEA', nextStep: 10 }, { label: 'ROSC', nextStep: 11 }] },
      { title: 'Defibrillate (2nd shock)', description: 'Biphasic: 120-200J. Resume CPR immediately.' },
      { title: 'CPR + Amiodarone', description: 'Continue CPR. Give amiodarone after 3rd shock.', timer: 120, timerLabel: 'CPR Timer (2 min)', medication: { drug: 'Amiodarone', dose: '300mg IV bolus', route: 'IV/IO — dilute in D5W' } },
      { title: 'Rhythm Check', description: 'Pause CPR. Analyze rhythm.', options: [{ label: 'Still VF/pVT — continue cycle', nextStep: 8, color: 'red' }, { label: 'Asystole / PEA', nextStep: 10 }, { label: 'ROSC', nextStep: 11 }] },
      { title: 'Defibrillate + Adrenaline', description: 'Shock. Resume CPR. Adrenaline 1mg IV every 3-5 min (alternate cycles).', timer: 120, timerLabel: 'CPR Timer (2 min)', medication: { drug: 'Adrenaline', dose: '1mg IV/IO', route: 'Every 3-5 minutes' }, warning: 'Consider: reversible causes (Hs and Ts)' },
      { title: 'Rhythm Check', description: 'Continue cycling: Shock → CPR 2min → Rhythm check. Adrenaline every other cycle. Amiodarone 150mg once more if needed.', options: [{ label: 'Continue VF/pVT cycle', nextStep: 8, color: 'red' }, { label: 'Asystole / PEA', nextStep: 10 }, { label: 'ROSC', nextStep: 11 }] },
      { title: 'Non-Shockable Rhythm', description: 'Switch to Asystole/PEA protocol.', isEnd: true, endMessage: 'Continue CPR. Adrenaline 1mg q3-5min. Treat reversible causes.' },
      { title: 'ROSC Achieved', description: 'Return of spontaneous circulation.', isEnd: true, endMessage: 'Post-cardiac arrest care: 12-lead ECG, target SpO2 94-98%, consider TTM, cath lab if STEMI.' },
    ],
  },
  {
    id: 'acls-pea', name: 'Adult Cardiac Arrest — PEA/Asystole', category: 'ACLS',
    description: 'Pulseless electrical activity / Asystole',
    steps: [
      { title: 'Start CPR', description: 'High-quality CPR. Rate 100-120/min, depth 5-6cm. Attach monitor.', timer: 120, timerLabel: 'CPR Timer (2 min)' },
      { title: 'Confirm Non-Shockable Rhythm', description: 'Asystole or organized electrical activity without pulse.', warning: 'Confirm asystole in 2 leads. Check gain settings.' },
      { title: 'Adrenaline ASAP', description: 'Give adrenaline as soon as IV/IO access obtained.', medication: { drug: 'Adrenaline', dose: '1mg IV/IO', route: 'Repeat every 3-5 min' } },
      { title: 'CPR 2 Minutes', description: 'Continue high-quality CPR. Consider advanced airway.', timer: 120, timerLabel: 'CPR Timer (2 min)' },
      { title: 'Rhythm Check', description: 'Pause CPR. Check rhythm and pulse.', options: [{ label: 'Still PEA/Asystole — continue', nextStep: 5, color: 'red' }, { label: 'Shockable rhythm', nextStep: 7 }, { label: 'ROSC', nextStep: 8 }] },
      { title: 'Treat Reversible Causes', description: 'Hs: Hypovolaemia, Hypoxia, Hydrogen ion (acidosis), Hypo/Hyperkalaemia, Hypothermia.\nTs: Tension pneumothorax, Tamponade, Toxins, Thrombosis (PE/MI).', medication: { drug: 'Adrenaline', dose: '1mg IV/IO', route: 'Every 3-5 minutes' }, timer: 120, timerLabel: 'CPR Timer (2 min)' },
      { title: 'Rhythm Check', description: 'Continue cycling. Adrenaline q3-5min. Address reversible causes.', options: [{ label: 'Continue PEA/Asystole', nextStep: 5, color: 'red' }, { label: 'Shockable rhythm', nextStep: 7 }, { label: 'ROSC', nextStep: 8 }] },
      { title: 'Shockable Rhythm Detected', description: 'Switch to VF/pVT protocol.', isEnd: true, endMessage: 'Switch to VF/pVT algorithm. Defibrillate immediately.' },
      { title: 'ROSC Achieved', description: 'Return of spontaneous circulation.', isEnd: true, endMessage: 'Post-cardiac arrest care: 12-lead ECG, target SpO2 94-98%, consider TTM.' },
    ],
  },
  {
    id: 'bradycardia', name: 'Bradycardia with Pulse', category: 'ACLS',
    description: 'Symptomatic bradycardia management',
    steps: [
      { title: 'Assess Adequacy of Perfusion', description: 'HR typically <50/min with symptoms. Signs: hypotension, altered mental status, chest pain, acute heart failure.', options: [{ label: 'Adequate perfusion — monitor', nextStep: 6 }, { label: 'Poor perfusion — treat', nextStep: 1, color: 'red' }] },
      { title: 'Atropine', description: 'First-line for symptomatic bradycardia.', medication: { drug: 'Atropine', dose: '0.5mg IV', route: 'May repeat q3-5min, max 3mg' } },
      { title: 'Assess Response', options: [{ label: 'Improved — monitor', nextStep: 6 }, { label: 'No improvement', nextStep: 3, color: 'red' }] },
      { title: 'Transcutaneous Pacing', description: 'Apply pacing pads. Start at 60bpm, increase mA until capture. Sedate if conscious.', warning: 'Verify mechanical capture (palpate pulse).' },
      { title: 'Consider Dopamine or Adrenaline Infusion', description: 'If pacing unavailable or as bridge.', medication: { drug: 'Dopamine', dose: '5-20 mcg/kg/min', route: 'IV infusion' }, warning: 'Alternative: Adrenaline 2-10 mcg/min IV infusion.' },
      { title: 'Arrange Expert Consultation', description: 'Consider transvenous pacing. Identify and treat underlying cause.', isEnd: true, endMessage: 'Cardiology consult for transvenous pacing.' },
      { title: 'Monitor', description: 'Continue monitoring. Observe for deterioration.', isEnd: true, endMessage: 'Identify and treat reversible cause (drugs, electrolytes, MI).' },
    ],
  },
  {
    id: 'anaphylaxis', name: 'Anaphylaxis', category: 'Emergency Medicine',
    description: 'Acute anaphylactic reaction management',
    steps: [
      { title: 'Recognise Anaphylaxis', description: 'Sudden onset (minutes to hours) involving skin AND at least one of: respiratory compromise, cardiovascular compromise, persistent severe GI symptoms.', warning: 'Remove trigger if possible. Call for help.' },
      { title: 'Adrenaline IM', description: 'FIRST-LINE treatment. Do not delay.', medication: { drug: 'Adrenaline (Epinephrine)', dose: '0.5mg IM (0.5mL of 1:1000)', route: 'IM anterolateral thigh' }, warning: 'IM, NOT IV for first dose (unless cardiac arrest). Can repeat every 5-15 min.' },
      { title: 'Position Patient', description: 'Lay flat with legs elevated (if tolerating). If breathing difficulty, allow to sit up. If pregnant, left lateral.', options: [{ label: 'Improving', nextStep: 5 }, { label: 'Not improving after 5 min', nextStep: 3, color: 'red' }] },
      { title: 'Repeat Adrenaline', description: 'Give second dose of adrenaline IM.', medication: { drug: 'Adrenaline', dose: '0.5mg IM', route: 'Repeat IM anterolateral thigh' } },
      { title: 'IV Fluid Bolus', description: 'If hypotensive: 500mL-1L crystalloid bolus rapidly.', medication: { drug: '0.9% Normal Saline', dose: '500mL-1L', route: 'IV rapid bolus' }, warning: 'If refractory: consider adrenaline IV infusion 0.1-1 mcg/kg/min in ICU setting.' },
      { title: 'Adjunctive Therapy', description: 'After adrenaline given:\n- Hydrocortisone 200mg IV (prevents biphasic reaction)\n- Chlorphenamine 10mg IM/IV (or cetirizine 10mg PO)\n- Salbutamol 5mg nebulised if bronchospasm', medication: { drug: 'Hydrocortisone', dose: '200mg IV', route: 'IV slow injection' } },
      { title: 'Observe and Disposition', description: 'Observe minimum 6-12 hours (24h if severe/biphasic features). Prescribe EpiPen. Refer to allergy clinic.', isEnd: true, endMessage: 'Document allergen. Prescribe auto-injector. Allergy clinic referral.' },
    ],
  },
  {
    id: 'sepsis-bundle', name: 'Sepsis / Septic Shock (Hour-1 Bundle)', category: 'Emergency Medicine',
    description: 'SSC Hour-1 Bundle for sepsis and septic shock',
    steps: [
      { title: 'Suspect Sepsis', description: 'Infection + organ dysfunction. qSOFA >= 2: SBP<=100, RR>=22, altered mentation.', warning: 'HOUR-1 BUNDLE: All steps should begin within 1 hour of recognition.' },
      { title: 'Measure Lactate', description: 'Send blood gas for lactate. If lactate > 2 mmol/L, remeasure within 2-4 hours.', warning: 'Lactate > 4 mmol/L = high mortality. Aggressive resuscitation needed.' },
      { title: 'Blood Cultures Before Antibiotics', description: 'At least 2 sets (aerobic + anaerobic) from 2 separate sites. Do NOT delay antibiotics for cultures if collection will take >45 min.' },
      { title: 'Broad-Spectrum Antibiotics', description: 'Give within 1 hour. Choice depends on source. Common empiric:', medication: { drug: 'Piperacillin-Tazobactam', dose: '4.5g IV', route: 'IV over 30 min' }, warning: 'If penicillin allergy: Meropenem 1g IV. Add Vancomycin if MRSA risk.' },
      { title: 'IV Fluid Resuscitation', description: 'If hypotensive or lactate >= 4 mmol/L:', medication: { drug: '0.9% Normal Saline', dose: '30 mL/kg', route: 'IV — give within first 3 hours' }, warning: 'Reassess volume status after each bolus. Be cautious in heart failure.' },
      { title: 'Vasopressors if Refractory Hypotension', description: 'If MAP < 65 despite fluids:', medication: { drug: 'Noradrenaline', dose: '0.1-0.5 mcg/kg/min', route: 'IV central line preferred' }, warning: 'Target MAP >= 65 mmHg. Can start peripherally while central line placed.' },
      { title: 'Reassess and Escalate', description: 'Reassess perfusion: lactate clearance, urine output, capillary refill. Consider: source control (drainage, debridement), stress-dose steroids if refractory shock, ICU admission.', isEnd: true, endMessage: 'Ongoing care: source control, lactate clearance, reassess antibiotics at 48h.' },
    ],
  },
  {
    id: 'dka', name: 'DKA Management', category: 'Emergency Medicine',
    description: 'Diabetic ketoacidosis protocol',
    steps: [
      { title: 'Confirm DKA', description: 'Blood glucose > 11 mmol/L (200 mg/dL) + Ketones (blood > 3 or urine 2+) + pH < 7.3 or bicarb < 15.', warning: 'Classify severity: Mild (pH 7.25-7.3), Moderate (7.0-7.24), Severe (<7.0).' },
      { title: 'IV Fluid Resuscitation', description: '0.9% NaCl 1L over 1 hour, then 1L over 2h, then 1L over 4h. Switch to 0.45% NaCl if Na > 155.', medication: { drug: '0.9% Normal Saline', dose: '1L over 1 hour', route: 'IV' } },
      { title: 'Potassium Replacement', description: 'Check K before starting insulin.\nK < 3.5: Replace K first, delay insulin.\nK 3.5-5.5: Add 40mmol KCl/L to fluids.\nK > 5.5: Do not add K, recheck in 2h.', warning: 'NEVER start insulin if K < 3.5 — risk of fatal arrhythmia.' },
      { title: 'Fixed-Rate Insulin Infusion', description: 'Start at 0.1 units/kg/h. Target: glucose drop 3-4 mmol/h, ketone drop 0.5 mmol/h, bicarb rise 3 mmol/h.', medication: { drug: 'Insulin (Actrapid/Humulin R)', dose: '0.1 units/kg/h', route: 'IV continuous infusion' } },
      { title: 'Add Dextrose When Glucose < 14', description: 'When glucose drops below 14 mmol/L (250 mg/dL), add 10% Dextrose alongside saline. Do NOT stop insulin until ketones cleared.', warning: 'Continue insulin even if glucose normalizes — the goal is to clear ketones.' },
      { title: 'Monitor', description: 'Hourly: glucose, ketones. 2-hourly: VBG (pH, bicarb, K). Continuous: ECG if K abnormal.', warning: 'Resolution criteria: pH > 7.3 AND bicarb > 15 AND ketones < 0.6' },
      { title: 'Transition to SC Insulin', description: 'When eating and DKA resolved: give SC insulin with a meal, then stop IV insulin 30-60 min later.', isEnd: true, endMessage: 'Identify precipitant (infection, non-compliance, new diagnosis). Diabetes team review.' },
    ],
  },
  {
    id: 'primary-survey', name: 'Primary Survey (ATLS ABCDE)', category: 'Trauma',
    description: 'ATLS primary survey systematic assessment',
    steps: [
      { title: 'A — Airway + C-spine', description: 'Assess patency. Look, listen, feel.\n- Jaw thrust (maintain c-spine)\n- Suction if needed\n- Definitive airway if GCS <=8', warning: 'Maintain manual in-line stabilization of c-spine throughout.' },
      { title: 'B — Breathing', description: 'Expose chest. Inspect, palpate, percuss, auscultate.\n- Respiratory rate, SpO2\n- Tracheal deviation?\n- Tension pneumothorax? → Decompress immediately\n- Open chest wound? → 3-sided dressing', options: [{ label: 'Tension pneumothorax', nextStep: 7, color: 'red' }, { label: 'No immediate threat — continue', nextStep: 2 }] },
      { title: 'C — Circulation + Hemorrhage Control', description: 'Control external hemorrhage: direct pressure, tourniquet if limb.\n- 2 large-bore IV (16G antecubital)\n- Bloods: FBC, XM, coags, lactate\n- Fluid: warm crystalloid 1L bolus, reassess', warning: 'Permissive hypotension if penetrating trauma (SBP target 80-90 mmHg until surgical control).' },
      { title: 'D — Disability', description: 'GCS (E + V + M)\nPupils: size, equality, reactivity\nLateralization?\nGlucose (exclude hypoglycaemia)\n\nGCS <= 8 → protect airway' },
      { title: 'E — Exposure + Environment', description: 'Fully undress patient. Log-roll to examine back.\nPrevent hypothermia: warm blankets, warm fluids, warm room.\nFull secondary survey when stable.' },
      { title: 'Reassess and Disposition', description: 'AMPLE history: Allergies, Medications, Past medical, Last meal, Events.\nXR: chest, pelvis (if indicated). FAST scan.\nDecide: OR, CT, ICU, or observation.', isEnd: true, endMessage: 'Document primary survey findings. Plan secondary survey.' },
      { title: 'Needle Decompression', description: 'Tension pneumothorax management:\n- 14G cannula, 2nd ICS MCL (or 4th/5th ICS MAL)\n- Rush of air confirms diagnosis\n- Follow with chest drain (28-32Fr)', warning: 'Do NOT delay for CXR if clinical diagnosis.' },
    ],
  },
  {
    id: 'status-epilepticus', name: 'Status Epilepticus', category: 'Emergency Medicine',
    description: 'Continuous seizure > 5 min or recurrent without recovery',
    steps: [
      { title: 'Initial Assessment (0-5 min)', description: 'Airway, breathing, circulation. Lateral position if possible. High-flow O2. IV access. Check glucose.', warning: 'Time the seizure. Status epilepticus = seizure > 5 min or 2+ without recovery.' },
      { title: 'First-Line: Benzodiazepine', description: 'Give immediately:', medication: { drug: 'Lorazepam', dose: '4mg IV (or Diazepam 10mg IV, or Midazolam 10mg IM/buccal)', route: 'IV preferred, IM if no access' }, warning: 'May repeat once after 5-10 min if still seizing.' },
      { title: 'Reassess at 5-10 min', options: [{ label: 'Seizure stopped', nextStep: 7 }, { label: 'Still seizing', nextStep: 3, color: 'red' }] },
      { title: 'Repeat Benzodiazepine', medication: { drug: 'Lorazepam', dose: '4mg IV (2nd dose)', route: 'IV' }, warning: 'Max 2 doses of benzodiazepine. Prepare 2nd line.' },
      { title: 'Second-Line: Antiepileptic', description: 'If still seizing after 2 doses benzodiazepine (10-20 min):', medication: { drug: 'Levetiracetam', dose: '60mg/kg IV (max 4.5g) over 10 min', route: 'IV' }, warning: 'Alternatives: Phenytoin 20mg/kg IV at max 50mg/min (with cardiac monitoring), or Sodium valproate 40mg/kg IV over 10 min.' },
      { title: 'Refractory Status (>30 min)', description: 'If still seizing after 2nd line agent: this is refractory status epilepticus. Requires ICU + anaesthetic support.', warning: 'Intubate and ventilate. Start thiopental, midazolam, or propofol infusion. Continuous EEG monitoring.', isEnd: true, endMessage: 'ICU admission for refractory SE. Continuous EEG. Investigate cause.' },
      { title: 'Post-Seizure Care', description: 'Recovery position. Monitor GCS, vitals. Investigate cause: CT head, LP if indicated, AED levels, metabolic panel.', isEnd: true, endMessage: 'Document seizure duration and treatment. Neurology review.' },
    ],
  },
  {
    id: 'acute-mi', name: 'Acute Coronary Syndrome', category: 'ACLS',
    description: 'STEMI and NSTEMI/UA initial management',
    steps: [
      { title: '12-Lead ECG', description: 'Obtain within 10 minutes of first contact. Interpret for ST changes.', warning: 'Do NOT delay aspirin for ECG.', options: [{ label: 'STEMI', nextStep: 1, color: 'red' }, { label: 'NSTEMI / UA', nextStep: 4, color: 'yellow' }] },
      { title: 'STEMI — Activate Cath Lab', description: 'Primary PCI is the goal. Door-to-balloon < 90 min.', warning: 'If PCI not available within 120 min, consider fibrinolysis.' },
      { title: 'STEMI Initial Treatment', description: 'MONA + anticoagulation:', medication: { drug: 'Aspirin', dose: '300mg PO chewed', route: 'STAT' }, warning: 'Also give: Ticagrelor 180mg (or Clopidogrel 600mg), Heparin per protocol. Morphine only if persistent pain.' },
      { title: 'STEMI — Cath Lab / Fibrinolysis', description: 'If PCI available: transfer to cath lab.\nIf PCI NOT available within 120 min: Tenecteplase weight-based IV bolus.', isEnd: true, endMessage: 'Post-PCI care: dual antiplatelet, statin, beta-blocker, ACEi when stable.' },
      { title: 'NSTEMI/UA — GRACE Score', description: 'Aspirin 300mg + Ticagrelor 180mg (or Clopidogrel 300mg).\nFondaparinux 2.5mg SC or Enoxaparin 1mg/kg SC q12h.\nRisk stratify: high-risk → early invasive (24-72h). Low-risk → conservative.', medication: { drug: 'Aspirin', dose: '300mg PO chewed + Ticagrelor 180mg', route: 'PO STAT' } },
      { title: 'Ongoing ACS Management', description: 'Beta-blocker (if no CI), high-intensity statin, ACEi, GTN PRN.\nSerial troponins at 0, 3, 6h.\nEchocardiogram.', isEnd: true, endMessage: 'Cardiology review for angiography timing. Dual antiplatelet therapy.' },
    ],
  },
  {
    id: 'paracetamol-od', name: 'Paracetamol Overdose', category: 'Toxicology',
    description: 'Paracetamol (Acetaminophen) overdose management',
    steps: [
      { title: 'History', description: 'Time of ingestion? Single acute or staggered? Amount (mg/kg)?\n- Toxic dose: > 150mg/kg or > 10g in adults\n- Consider risk factors: chronic alcohol, enzyme inducers, malnutrition', warning: 'Staggered overdose or unknown time → treat empirically.' },
      { title: 'Initial Assessment', description: 'Bloods: paracetamol level (at 4h post-ingestion), LFTs, INR, creatinine, venous blood gas, lactate.\nIf < 1h post-ingestion AND > 150mg/kg: give activated charcoal 50g PO.' },
      { title: 'Plot on Nomogram', description: 'Plot paracetamol level at 4h (or later) on treatment nomogram.\nUK: use 100mg/L line at 4h.\nUS: Rumack-Matthew nomogram.', options: [{ label: 'Above treatment line → NAC', nextStep: 3, color: 'red' }, { label: 'Below line → observe', nextStep: 5 }, { label: 'Staggered/unknown time', nextStep: 3, color: 'amber' }] },
      { title: 'N-Acetylcysteine (NAC)', description: 'Modified 2-bag regimen:\nBag 1: 200mg/kg in 500mL 5% dextrose over 4h\nBag 2: 100mg/kg in 1L 5% dextrose over 16h', medication: { drug: 'N-Acetylcysteine (NAC)', dose: '200mg/kg IV over 4h, then 100mg/kg over 16h', route: 'IV in 5% dextrose' }, warning: 'Anaphylactoid reactions common — slow infusion and treat with antihistamine. Do NOT stop NAC.' },
      { title: 'Monitor During NAC', description: 'Recheck at end of infusion: ALT, INR, creatinine, paracetamol level.\nContinue NAC if: ALT rising, INR > 1.3, paracetamol still detectable.', options: [{ label: 'Improving — complete NAC', nextStep: 5 }, { label: 'Worsening → liver failure', nextStep: 6, color: 'red' }] },
      { title: 'Discharge Criteria', description: 'Paracetamol undetectable, ALT normal or falling, INR normal, clinically well. Psychiatric assessment if intentional.', isEnd: true, endMessage: 'Ensure psychiatric review before discharge if intentional overdose.' },
      { title: 'Acute Liver Failure', description: 'Contact liver transplant centre. Kings College Criteria for transplant listing.\nContinue NAC. Manage coagulopathy, hypoglycaemia, cerebral oedema.', isEnd: true, endMessage: 'ICU admission. Liver transplant centre referral.' },
    ],
  },
];
