// OCR Seed — Anatomy, Symptoms, Physical Exam, Eponyms, ICD patterns
// ~3000 terms covering every body system, every symptom, every exam finding

export const ANATOMY = [
  // Head & Skull
  'Frontal bone','Parietal bone','Temporal bone','Occipital bone','Sphenoid','Ethmoid',
  'Cranium','Calvaria','Skull base','Anterior fossa','Middle fossa','Posterior fossa',
  'Foramen magnum','Sella turcica','Clivus','Petrous bone','Mastoid process',
  'Zygomatic arch','Mandible','Maxilla','TMJ','Temporomandibular joint',
  'Scalp','Galea','Subgaleal','Epidural space','Subdural space','Subarachnoid space',
  // Brain
  'Cerebrum','Cerebral cortex','Frontal lobe','Parietal lobe','Temporal lobe','Occipital lobe',
  'Insula','Cingulate gyrus','Hippocampus','Amygdala','Basal ganglia',
  'Caudate nucleus','Putamen','Globus pallidus','Thalamus','Hypothalamus',
  'Cerebellum','Cerebellar vermis','Cerebellar hemisphere',
  'Brainstem','Midbrain','Pons','Medulla oblongata',
  'Corpus callosum','Internal capsule','External capsule','Corona radiata',
  'Lateral ventricle','Third ventricle','Fourth ventricle','Aqueduct of Sylvius',
  'Choroid plexus','Foramen of Monro','Foramen of Luschka','Foramen of Magendie',
  'Circle of Willis','MCA','ACA','PCA','Basilar artery','Vertebral artery',
  'Carotid artery','Internal carotid','External carotid','Carotid bifurcation',
  'Superior sagittal sinus','Transverse sinus','Sigmoid sinus','Cavernous sinus',
  'Meninges','Dura mater','Arachnoid mater','Pia mater',
  'Cranial nerves','CN I','Olfactory','CN II','Optic','CN III','Oculomotor',
  'CN IV','Trochlear','CN V','Trigeminal','CN VI','Abducens',
  'CN VII','Facial','CN VIII','Vestibulocochlear','CN IX','Glossopharyngeal',
  'CN X','Vagus','CN XI','Accessory','CN XII','Hypoglossal',
  // Spine
  'Cervical spine','C-spine','C1','C2','C3','C4','C5','C6','C7',
  'Thoracic spine','T-spine','T1','T2','T3','T4','T5','T6','T7','T8','T9','T10','T11','T12',
  'Lumbar spine','L-spine','L1','L2','L3','L4','L5',
  'Sacrum','S1','S2','S3','S4','S5','Coccyx',
  'Vertebral body','Spinous process','Transverse process','Pedicle','Lamina',
  'Intervertebral disc','Nucleus pulposus','Annulus fibrosus',
  'Spinal cord','Conus medullaris','Cauda equina','Filum terminale',
  'Spinal canal','Neural foramen','Intervertebral foramen',
  'Anterior longitudinal ligament','ALL','Posterior longitudinal ligament','PLL',
  'Ligamentum flavum','Interspinous ligament',
  // Eye
  'Cornea','Iris','Pupil','Lens','Retina','Macula','Fovea',
  'Optic disc','Optic nerve','Optic chiasm','Optic tract',
  'Vitreous','Aqueous humor','Anterior chamber','Posterior chamber',
  'Conjunctiva','Sclera','Choroid','Ciliary body',
  'Lacrimal gland','Lacrimal duct','Nasolacrimal duct',
  'Extraocular muscles','Superior rectus','Inferior rectus',
  'Lateral rectus','Medial rectus','Superior oblique','Inferior oblique',
  'Eyelid','Upper lid','Lower lid','Tarsal plate','Meibomian gland',
  // Ear
  'External ear','Auricle','Pinna','External auditory canal','EAC',
  'Tympanic membrane','TM','Eardrum',
  'Middle ear','Ossicles','Malleus','Incus','Stapes','Eustachian tube',
  'Inner ear','Cochlea','Semicircular canals','Vestibule',
  'Mastoid','Mastoid air cells',
  // Nose & Sinuses
  'Nasal septum','Inferior turbinate','Middle turbinate','Superior turbinate',
  'Maxillary sinus','Frontal sinus','Ethmoid sinus','Sphenoid sinus',
  'Nasal cavity','Nasopharynx','Oropharynx','Hypopharynx','Larynx',
  'Epiglottis','Vocal cords','Glottis','Subglottis','Trachea',
  // Neck
  'Thyroid gland','Thyroid isthmus','Thyroid lobe',
  'Parathyroid glands','Submandibular gland','Parotid gland',
  'Carotid sheath','Jugular vein','Internal jugular','External jugular',
  'Sternocleidomastoid','SCM','Trapezius',
  'Cervical lymph nodes','Supraclavicular nodes','Posterior triangle','Anterior triangle',
  'Hyoid bone','Thyroid cartilage','Cricoid cartilage',
  // Thorax
  'Sternum','Manubrium','Body of sternum','Xiphoid process',
  'Ribs','True ribs','False ribs','Floating ribs','Costal cartilage',
  'Intercostal space','ICS','Intercostal muscles',
  'Thoracic cavity','Mediastinum','Anterior mediastinum','Middle mediastinum','Posterior mediastinum',
  'Pleura','Visceral pleura','Parietal pleura','Pleural space','Pleural cavity',
  'Diaphragm','Right hemidiaphragm','Left hemidiaphragm',
  'Costophrenic angle','CP angle','Cardiophrenic angle',
  // Lungs
  'Right lung','Left lung','Right upper lobe','RUL','Right middle lobe','RML',
  'Right lower lobe','RLL','Left upper lobe','LUL','Lingula','Left lower lobe','LLL',
  'Main bronchus','Right main bronchus','Left main bronchus',
  'Lobar bronchus','Segmental bronchus','Bronchiole','Terminal bronchiole',
  'Alveolus','Alveoli','Alveolar sac',
  'Hilum','Right hilum','Left hilum','Hilar',
  'Pulmonary artery','Main pulmonary artery','MPA',
  'Right pulmonary artery','RPA','Left pulmonary artery','LPA',
  'Pulmonary vein','Superior pulmonary vein','Inferior pulmonary vein',
  'Carina','Tracheal bifurcation',
  // Heart
  'Right atrium','RA','Left atrium','LA',
  'Right ventricle','RV','Left ventricle','LV',
  'Interventricular septum','IVS','Interatrial septum','IAS',
  'Mitral valve','MV','Aortic valve','AV','Tricuspid valve','TV','Pulmonic valve','PV',
  'Aorta','Ascending aorta','Aortic arch','Descending aorta','Aortic root',
  'Superior vena cava','SVC','Inferior vena cava','IVC',
  'Coronary arteries','LAD','Left anterior descending',
  'LCx','Left circumflex','RCA','Right coronary artery',
  'Left main','LMCA','Left main coronary artery',
  'Pericardium','Pericardial space','Epicardium','Myocardium','Endocardium',
  'Papillary muscle','Chordae tendineae','Cardiac apex',
  'SA node','Sinoatrial node','AV node','Atrioventricular node',
  'Bundle of His','Right bundle branch','RBB','Left bundle branch','LBB',
  'Purkinje fibers',
  // Abdomen
  'Peritoneum','Peritoneal cavity','Retroperitoneum',
  'Omentum','Greater omentum','Lesser omentum','Mesentery',
  'Esophagus','Lower esophageal sphincter','LES','GEJ','Gastroesophageal junction',
  'Stomach','Fundus','Body of stomach','Antrum','Pylorus','Pyloric sphincter',
  'Duodenum','D1','D2','D3','D4','Ampulla of Vater','Papilla of Vater',
  'Jejunum','Ileum','Ileocecal valve',
  'Cecum','Appendix','Ascending colon','Hepatic flexure',
  'Transverse colon','Splenic flexure','Descending colon','Sigmoid colon',
  'Rectum','Rectosigmoid','Anal canal','Anus','Anal sphincter',
  'Liver','Right lobe of liver','Left lobe of liver','Caudate lobe','Quadrate lobe',
  'Hepatic segments','Segment I','Segment II','Segment III','Segment IV',
  'Segment V','Segment VI','Segment VII','Segment VIII',
  'Porta hepatis','Portal vein','Hepatic artery','Hepatic vein',
  'Hepatic duct','Common hepatic duct','Common bile duct','CBD',
  'Gallbladder','Gallbladder fundus','Gallbladder body','Gallbladder neck',
  'Cystic duct','Hartmann pouch',
  'Pancreas','Pancreatic head','Pancreatic body','Pancreatic tail',
  'Pancreatic duct','Wirsung duct','Santorini duct','Uncinate process',
  'Spleen','Splenic hilum','Splenic artery','Splenic vein',
  'Adrenal gland','Right adrenal','Left adrenal','Adrenal cortex','Adrenal medulla',
  // Kidneys & Urinary
  'Kidney','Right kidney','Left kidney','Renal cortex','Renal medulla',
  'Renal pelvis','Renal calyx','Major calyx','Minor calyx',
  'Renal artery','Renal vein','Renal hilum',
  'Ureter','Right ureter','Left ureter','UPJ','Ureteropelvic junction',
  'UVJ','Ureterovesical junction','VUJ',
  'Bladder','Urinary bladder','Bladder dome','Bladder neck','Trigone',
  'Urethra','Prostatic urethra','Membranous urethra','Penile urethra',
  'Prostate','Prostate gland','Seminal vesicles',
  // Pelvis & Reproductive
  'Uterus','Uterine fundus','Uterine body','Cervix','Endometrium','Myometrium',
  'Fallopian tube','Ovary','Right ovary','Left ovary',
  'Vagina','Vulva','Perineum',
  'Testis','Epididymis','Spermatic cord','Vas deferens',
  'Pelvic floor','Levator ani','Obturator internus',
  'Iliac vessels','Common iliac','External iliac','Internal iliac',
  'Femoral vessels','Femoral artery','Femoral vein',
  // Upper Extremity
  'Shoulder','Glenohumeral joint','Acromioclavicular joint','AC joint',
  'Clavicle','Scapula','Acromion','Coracoid process',
  'Humerus','Humeral head','Greater tuberosity','Lesser tuberosity',
  'Humeral shaft','Lateral epicondyle','Medial epicondyle',
  'Rotator cuff','Supraspinatus','Infraspinatus','Teres minor','Subscapularis',
  'Deltoid','Biceps','Triceps','Brachialis',
  'Elbow','Olecranon','Radial head','Coronoid process',
  'Radius','Ulna','Radial shaft','Ulnar shaft',
  'Wrist','Carpal bones','Scaphoid','Lunate','Triquetrum','Pisiform',
  'Trapezium','Trapezoid','Capitate','Hamate',
  'Metacarpals','Phalanges','Proximal phalanx','Middle phalanx','Distal phalanx',
  'Thumb','Index finger','Middle finger','Ring finger','Little finger',
  'Radial artery','Ulnar artery','Brachial artery',
  'Median nerve','Ulnar nerve','Radial nerve','Musculocutaneous nerve',
  'Brachial plexus','Axillary nerve',
  // Lower Extremity
  'Hip','Hip joint','Acetabulum','Femoral head','Femoral neck',
  'Greater trochanter','Lesser trochanter','Intertrochanteric',
  'Femur','Femoral shaft','Femoral condyle',
  'Knee','Patella','Tibial plateau','Intercondylar notch',
  'ACL','Anterior cruciate ligament','PCL','Posterior cruciate ligament',
  'MCL','Medial collateral ligament','LCL','Lateral collateral ligament',
  'Medial meniscus','Lateral meniscus',
  'Tibia','Tibial shaft','Fibula','Fibular shaft',
  'Ankle','Medial malleolus','Lateral malleolus','Posterior malleolus',
  'Talus','Calcaneus','Navicular','Cuboid',
  'Cuneiforms','Metatarsals','Toes','Hallux','Great toe',
  'Achilles tendon','Calcaneal tendon',
  'Femoral artery','Popliteal artery','Anterior tibial artery','Posterior tibial artery',
  'Dorsalis pedis artery','DP artery',
  'Femoral nerve','Sciatic nerve','Common peroneal nerve','Tibial nerve',
  'Sural nerve','Saphenous nerve',
  'Quadriceps','Hamstrings','Gastrocnemius','Soleus','Tibialis anterior',
  // Lymphatic
  'Cervical lymph nodes','Axillary lymph nodes','Inguinal lymph nodes',
  'Mediastinal lymph nodes','Hilar lymph nodes','Mesenteric lymph nodes',
  'Retroperitoneal lymph nodes','Para-aortic lymph nodes',
  'Supraclavicular lymph node','Virchow node',
  'Thoracic duct','Cisterna chyli','Spleen','Thymus',
];

export const COMPREHENSIVE_SYMPTOMS = [
  // Constitutional
  'Fatigue','Malaise','Lethargy','Weakness','Asthenia',
  'Weight loss','Weight gain','Unintentional weight loss',
  'Appetite loss','Anorexia','Poor appetite','Increased appetite','Polyphagia',
  'Fever','Chills','Rigors','Night sweats','Diaphoresis','Cold sweats',
  'Flushing','Hot flashes',
  // HEENT
  'Blurred vision','Double vision','Diplopia','Visual loss','Scotoma',
  'Floaters','Flashes','Photophobia','Eye pain','Red eye','Tearing','Dry eyes',
  'Ear pain','Otalgia','Hearing loss','Tinnitus','Vertigo','Ear discharge','Otorrhea',
  'Nasal congestion','Rhinorrhea','Runny nose','Sneezing','Epistaxis','Nosebleed',
  'Anosmia','Loss of smell','Ageusia','Loss of taste',
  'Sore throat','Pharyngitis','Dysphagia','Odynophagia',
  'Hoarseness','Dysphonia','Voice change',
  'Dry mouth','Xerostomia','Excessive salivation','Sialorrhea',
  'Toothache','Dental pain','Jaw pain','TMJ pain','Trismus','Lockjaw',
  // Neurological
  'Headache','Migraine','Tension headache','Cluster headache',
  'Dizziness','Lightheadedness','Presyncope','Syncope','Fainting',
  'Vertigo','Room spinning','Unsteadiness','Ataxia','Incoordination',
  'Seizure','Convulsion','Tremor','Trembling','Shaking',
  'Numbness','Tingling','Paresthesia','Pins and needles',
  'Weakness','Paresis','Paralysis','Plegia','Hemiplegia','Hemiparesis',
  'Facial droop','Facial weakness','Slurred speech','Dysarthria',
  'Aphasia','Word finding difficulty','Confusion','Disorientation',
  'Memory loss','Amnesia','Cognitive decline','Forgetfulness',
  'Insomnia','Sleep difficulty','Hypersomnia','Excessive sleepiness',
  'Restlessness','Agitation','Anxiety','Nervousness',
  'Depression','Low mood','Sadness','Crying spells',
  'Hallucinations','Delusions','Paranoia','Psychosis',
  // Cardiovascular
  'Chest pain','Chest tightness','Chest pressure','Chest heaviness',
  'Palpitations','Heart racing','Irregular heartbeat','Skipped beats',
  'Orthopnea','PND','Paroxysmal nocturnal dyspnea',
  'Leg swelling','Ankle swelling','Pedal edema',
  'Claudication','Leg pain with walking','Rest pain',
  'Cold extremities','Pallor','Cyanosis',
  // Respiratory
  'Shortness of breath','Dyspnea','Breathlessness',
  'Cough','Productive cough','Dry cough','Chronic cough',
  'Hemoptysis','Coughing blood','Blood-tinged sputum',
  'Wheezing','Stridor','Noisy breathing',
  'Pleuritic pain','Sharp chest pain with breathing',
  'Sputum production','Purulent sputum','Green sputum',
  // GI
  'Nausea','Vomiting','Retching','Dry heaving',
  'Abdominal pain','Stomach pain','Belly pain','Cramps','Cramping',
  'Heartburn','Acid reflux','Pyrosis','Regurgitation',
  'Dyspepsia','Indigestion','Bloating','Distension','Gas','Flatulence',
  'Diarrhea','Loose stools','Watery stools','Bloody stool',
  'Constipation','Straining','Hard stools','Incomplete evacuation',
  'Melena','Black stool','Hematochezia','Bright red blood per rectum',
  'Dysphagia','Difficulty swallowing','Food getting stuck',
  'Odynophagia','Painful swallowing',
  'Jaundice','Yellow skin','Yellow eyes','Icterus',
  'Pruritus','Itching','Generalized itching',
  'Ascites','Abdominal distension','Abdominal swelling',
  'Tenesmus','Urgency','Fecal incontinence',
  // GU
  'Dysuria','Painful urination','Burning urination',
  'Frequency','Urinary frequency','Nocturia','Getting up at night',
  'Urgency','Urinary urgency','Urge incontinence',
  'Hesitancy','Weak stream','Incomplete emptying',
  'Hematuria','Blood in urine','Dark urine','Cola-colored urine',
  'Oliguria','Decreased urine output','Anuria','No urine',
  'Polyuria','Excessive urination','Polydipsia','Excessive thirst',
  'Flank pain','Kidney pain','Suprapubic pain','Bladder pain',
  'Urinary incontinence','Stress incontinence','Overflow incontinence',
  'Urinary retention','Unable to void','Foley placed',
  'Penile discharge','Vaginal discharge','Vaginal bleeding',
  'Menorrhagia','Heavy periods','Amenorrhea','Missed periods',
  'Dysmenorrhea','Painful periods','Intermenstrual bleeding',
  'Erectile dysfunction','ED','Impotence',
  // MSK
  'Joint pain','Arthralgia','Joint swelling','Joint stiffness',
  'Back pain','Low back pain','LBP','Upper back pain','Neck pain',
  'Sciatica','Radiculopathy','Shooting pain down leg',
  'Muscle pain','Myalgia','Muscle weakness','Muscle cramps','Spasms',
  'Bone pain','Tenderness','Point tenderness',
  'Limited range of motion','Stiffness','Morning stiffness',
  'Gait disturbance','Limp','Antalgic gait',
  'Deformity','Swelling','Effusion','Crepitus',
  // Skin
  'Rash','Skin rash','Eruption','Lesion',
  'Itching','Pruritus','Scratching',
  'Hives','Urticaria','Welts',
  'Blistering','Vesicles','Bullae',
  'Bruising','Ecchymosis','Petechiae','Purpura',
  'Wound','Laceration','Abrasion','Ulcer','Sore',
  'Cellulitis','Redness','Erythema','Warmth','Swelling',
  'Abscess','Boil','Furuncle','Carbuncle',
  'Hair loss','Alopecia',
  'Nail changes','Clubbing','Koilonychia','Onychomycosis',
  'Skin discoloration','Hyperpigmentation','Hypopigmentation',
  'Mole','Nevus','Skin tag','Wart',
  'Dry skin','Xerosis','Scaling','Flaking',
];

export const MEDICAL_EPONYMS = [
  'Addison disease','Alzheimer disease','Barlow syndrome','Barrett esophagus',
  'Basedow disease','Bell palsy','Boerhaave syndrome','Bouchard nodes',
  'Buerger disease','Budd-Chiari syndrome','Burkitt lymphoma',
  'Caroli disease','Chagas disease','Charcot joint','Charcot triad',
  'Conn syndrome','Crohn disease','Cushing syndrome','Cushing disease',
  'De Quervain thyroiditis','De Quervain tenosynovitis',
  'Dressler syndrome','Duchenne muscular dystrophy',
  'Dupuytren contracture','Eisenmenger syndrome',
  'Felty syndrome','Fournier gangrene',
  'Friedreich ataxia','Gardner syndrome',
  'Gilbert syndrome','Goodpasture syndrome',
  'Graves disease','Guillain-Barre syndrome',
  'Hashimoto thyroiditis','Heberden nodes',
  'Henoch-Schonlein purpura','Hirschsprung disease',
  'Hodgkin lymphoma','Horner syndrome',
  'Huntington disease','Kaposi sarcoma',
  'Kawasaki disease','Klinefelter syndrome',
  'Korsakoff syndrome','Leriche syndrome',
  'Lynch syndrome','Mallory-Weiss tear',
  'Marfan syndrome','Meckel diverticulum',
  'Meniere disease','Morrison pouch',
  'Murphy sign','Nikolsky sign','Osler nodes',
  'Paget disease','Parkinson disease',
  'Peutz-Jeghers syndrome','Plummer-Vinson syndrome',
  'Prinzmetal angina','Raynaud phenomenon',
  'Reiter syndrome','Roth spots',
  'Sjögren syndrome','Stevens-Johnson syndrome',
  'Still disease','Takayasu arteritis',
  'Todd paralysis','Trousseau sign','Trousseau syndrome',
  'Turner syndrome','Virchow triad','Virchow node',
  'Von Willebrand disease','Wallenberg syndrome',
  'Weber syndrome','Wenckebach','Wernicke encephalopathy',
  'Whipple disease','Wilson disease','Wolff-Parkinson-White',
  'Zenker diverticulum','Zollinger-Ellison syndrome',
  // Signs
  'Brudzinski sign','Kernig sign','Babinski sign','Romberg sign',
  'Trendelenburg sign','Lhermitte sign','Chvostek sign',
  'Trousseau sign','Kussmaul sign','Cullen sign','Grey Turner sign',
  'McBurney point','Rovsing sign','Psoas sign','Obturator sign',
  'Battle sign','Raccoon eyes','Halo sign',
  'Homans sign','Murphy sign','Courvoisier sign',
  'Janeway lesions','Osler nodes','Splinter hemorrhages',
  'Virchow triad','Beck triad','Cushing triad',
  'Charcot triad','Reynolds pentad',
  'Whipple triad','Samter triad',
];

export const ICD_PATTERNS = [
  // ICD-10 code patterns the OCR might encounter
  'I10','I11','I12','I13','I15','I20','I21','I22','I24','I25',
  'I26','I27','I28','I30','I31','I33','I34','I35','I36','I37',
  'I38','I39','I40','I42','I44','I45','I46','I47','I48','I49','I50',
  'I60','I61','I62','I63','I64','I65','I66','I67','I69',
  'I70','I71','I72','I73','I74','I77','I80','I82','I83',
  'J06','J09','J10','J11','J12','J13','J14','J15','J16','J17','J18',
  'J20','J21','J22','J40','J41','J42','J43','J44','J45','J46',
  'J47','J60','J80','J81','J84','J90','J93','J94','J96',
  'K20','K21','K22','K25','K26','K27','K29','K35','K40','K41',
  'K50','K51','K52','K55','K56','K57','K59','K65',
  'K70','K71','K72','K73','K74','K75','K76','K80','K81','K83','K85','K86',
  'N00','N01','N02','N03','N04','N05','N10','N11','N12','N13',
  'N17','N18','N19','N20','N23','N28','N30','N39','N40',
  'E10','E11','E13','E14','E05','E06','E16','E21','E22','E23','E24','E25','E27',
  'E40','E41','E43','E44','E46','E66','E78','E83','E84','E86','E87',
  'G00','G03','G04','G06','G20','G25','G30','G35','G40','G41','G43','G45',
  'G47','G50','G51','G56','G57','G60','G61','G62','G70','G71','G80','G81',
  'D50','D56','D57','D58','D59','D60','D61','D64','D65','D66','D67','D68','D69',
  'D70','D72','D73','D75','D76',
  'A00','A01','A02','A03','A04','A05','A06','A09','A15','A16',
  'A30','A31','A39','A40','A41','A46','A49',
  'B00','B01','B02','B05','B06','B15','B16','B17','B18','B19',
  'B20','B24','B25','B37','B44','B45','B50','B54','B58','B59',
  'C00','C15','C16','C18','C20','C22','C25','C34','C43','C44',
  'C50','C53','C54','C56','C61','C64','C67','C71','C73','C78','C79','C80',
  'C81','C82','C83','C85','C90','C91','C92','C95',
  'M05','M06','M10','M13','M15','M16','M17','M19','M20','M25',
  'M32','M33','M34','M35','M45','M47','M48','M50','M51','M54',
  'M62','M65','M70','M75','M79','M80','M81','M84','M86',
  'S00','S01','S02','S06','S09','S12','S13','S14','S22','S27',
  'S32','S42','S43','S49','S52','S62','S72','S82','S92',
  'T14','T15','T17','T18','T20','T30','T31','T36','T39','T40','T42','T43',
  'T50','T51','T56','T58','T59','T63','T65','T71','T78','T79','T80','T81',
  'R00','R03','R04','R05','R06','R07','R09','R10','R11','R13','R14',
  'R17','R18','R19','R20','R21','R22','R25','R26','R27','R29',
  'R30','R31','R32','R33','R34','R35','R39','R40','R41','R42',
  'R47','R50','R51','R52','R53','R55','R56','R57','R58','R59',
  'R60','R63','R68','R73','R78','R79','R91','R94',
  'Z00','Z01','Z03','Z09','Z13','Z20','Z23','Z29','Z30',
  'Z51','Z53','Z71','Z72','Z76','Z80','Z85','Z86','Z87','Z91','Z99',
  'F01','F02','F03','F05','F06','F10','F11','F12','F13','F14','F15',
  'F19','F20','F22','F23','F25','F30','F31','F32','F33','F34',
  'F40','F41','F42','F43','F44','F45','F48','F50','F51','F60','F70','F84','F90',
];

// Dosing patterns OCR encounters
export const DOSING_PATTERNS = [
  'mg','mcg','g','kg','mL','L','units','IU','mEq',
  'mg/kg','mcg/kg','mg/kg/hr','mcg/kg/min','units/hr','mL/hr',
  'mg PO','mg IV','mg IM','mg SC','mg SL','mg PR','mg INH','mg TOP',
  'once daily','twice daily','three times daily','four times daily',
  'QD','BID','TID','QID','Q4H','Q6H','Q8H','Q12H','Q24H',
  'q4h','q6h','q8h','q12h','q24h','q2h','q1h',
  'PRN','as needed','p.r.n.','prn',
  'STAT','stat','immediately','now',
  'before meals','after meals','with meals','at bedtime',
  'AC','PC','HS','QHS','QPM','QAM',
  'loading dose','maintenance dose','bolus','infusion',
  'taper','weaning dose','step down','titrate',
  'max dose','maximum dose','minimum dose',
  'round','round to nearest','give or take',
  'hold if','hold for','do not give if',
  'with food','on empty stomach','with water',
  'crush','do not crush','do not chew','swallow whole',
  'dissolve','sublingual','buccal','topical','rectal',
  'left eye','right eye','both eyes','OU','OD','OS',
  'left ear','right ear','both ears','AU','AD','AS',
  'each nostril','per nostril',
  'patch','transdermal','apply to',
];

export function loadAnatomySeedData(models) {
  const now = new Date().toISOString();
  const allTerms = [...ANATOMY, ...COMPREHENSIVE_SYMPTOMS, ...MEDICAL_EPONYMS, ...ICD_PATTERNS, ...DOSING_PATTERNS];
  for (const term of allTerms) {
    const key = term.toLowerCase();
    if (key.length < 2) continue;
    if (!models.diagnoses[key]) {
      models.diagnoses[key] = { count: 1, entity: 'CLINICAL_TERM', lastSeen: now, confidence: 0.62, seeded: true };
    }
  }
  models.anatomySeeded = true;
  return models;
}
