// OCR Mega Seed — massive vocabulary expansion
// Covers: every medical specialty exhaustively, surgical procedures,
// anesthesia, radiology reports, pathology, microbiology organisms,
// pharmacology classes, drug interactions, allergy/adverse reactions,
// medical devices, wound care, rehabilitation, pediatrics, OB/GYN,
// psychiatry, ophthalmology, ENT, urology, orthopedics, and
// thousands more OCR correction patterns.

// ═══════════════════════════════════════════════════════════════════
// SURGICAL PROCEDURES — every common operation
// ═══════════════════════════════════════════════════════════════════

export const SURGICAL_PROCEDURES = [
  // General surgery
  'Appendectomy','Laparoscopic appendectomy','Open appendectomy',
  'Cholecystectomy','Laparoscopic cholecystectomy','Open cholecystectomy',
  'Hernia repair','Inguinal hernia repair','Umbilical hernia repair',
  'Incisional hernia repair','Ventral hernia repair','Mesh repair',
  'Colectomy','Right hemicolectomy','Left hemicolectomy','Sigmoid colectomy',
  'Total colectomy','Subtotal colectomy','Low anterior resection','LAR',
  'Abdominoperineal resection','APR','Hartmann procedure',
  'Small bowel resection','Stricturoplasty','Adhesiolysis',
  'Gastrectomy','Partial gastrectomy','Total gastrectomy','Sleeve gastrectomy',
  'Roux-en-Y gastric bypass','RYGB','Gastric banding',
  'Whipple procedure','Pancreaticoduodenectomy','Distal pancreatectomy',
  'Splenectomy','Laparoscopic splenectomy',
  'Thyroidectomy','Total thyroidectomy','Hemithyroidectomy','Thyroid lobectomy',
  'Parathyroidectomy','Adrenalectomy',
  'Mastectomy','Lumpectomy','Sentinel lymph node biopsy','SLNB',
  'Axillary lymph node dissection','ALND',
  'Excisional biopsy','Incisional biopsy','Core needle biopsy','FNA',
  'Laparotomy','Exploratory laparotomy','Diagnostic laparoscopy',
  'Damage control surgery','DCS','Damage control laparotomy',
  'Feeding jejunostomy','Feeding gastrostomy','PEG placement',
  'Tracheostomy','Percutaneous tracheostomy','Surgical tracheostomy',
  'Central line insertion','PICC insertion','Port placement',
  'Chest tube insertion','Thoracotomy','VATS',
  'Video-assisted thoracoscopic surgery',
  'Lobectomy','Pneumonectomy','Wedge resection','Segmentectomy',
  'Mediastinoscopy','Bronchoscopy','Rigid bronchoscopy',
  // Vascular surgery
  'Carotid endarterectomy','CEA','Carotid stenting','CAS',
  'Aortic repair','Open aortic repair','EVAR','Endovascular aortic repair',
  'TEVAR','Thoracic endovascular aortic repair',
  'Femoral-popliteal bypass','Fem-pop bypass',
  'Aortobifemoral bypass','Axillofemoral bypass',
  'AV fistula','AVF','AV graft','AVG','Fistula creation',
  'Embolectomy','Thrombectomy','Fasciotomy',
  'Varicose vein surgery','Vein stripping','Endovenous ablation',
  'IVC filter placement','IVC filter retrieval',
  // Cardiac surgery
  'CABG','Coronary artery bypass grafting','Off-pump CABG','OPCAB',
  'Aortic valve replacement','AVR','Mitral valve replacement','MVR',
  'Mitral valve repair','Tricuspid valve repair',
  'TAVR','Transcatheter aortic valve replacement','TAVI',
  'MitraClip','Septal myectomy','Maze procedure',
  'Pericardiectomy','Pericardial window',
  'Ventricular assist device','VAD','LVAD','HeartMate','HeartWare',
  'Heart transplant','Cardiac transplantation',
  // Neurosurgery
  'Craniotomy','Craniectomy','Decompressive craniectomy',
  'Burr hole','Subdural evacuation','Epidural evacuation',
  'Hematoma evacuation','Clipping','Coiling',
  'Tumor resection','Brain tumor excision','Transsphenoidal surgery',
  'Ventriculoperitoneal shunt','VP shunt','VPS',
  'External ventricular drain','EVD placement',
  'Spinal fusion','Laminectomy','Discectomy','Microdiscectomy',
  'Anterior cervical discectomy and fusion','ACDF',
  'Posterior spinal fusion','PSF','Spinal decompression',
  'Deep brain stimulation','DBS',
  // Orthopedic surgery
  'ORIF','Open reduction internal fixation',
  'Closed reduction','External fixation',
  'Intramedullary nailing','IMN','Plate fixation',
  'Total hip replacement','THR','Total hip arthroplasty','THA',
  'Total knee replacement','TKR','Total knee arthroplasty','TKA',
  'Partial knee replacement','Unicompartmental knee arthroplasty','UKA',
  'Total shoulder replacement','Reverse shoulder arthroplasty',
  'Hip hemiarthroplasty','Bipolar hemiarthroplasty',
  'Dynamic hip screw','DHS','Cannulated screws',
  'Arthroscopy','Knee arthroscopy','Shoulder arthroscopy',
  'ACL reconstruction','Meniscectomy','Meniscal repair',
  'Rotator cuff repair','Bankart repair','Labral repair',
  'Carpal tunnel release','CTR','Trigger finger release',
  'Tendon repair','Tendon transfer','Tenolysis',
  'Amputation','Above knee amputation','AKA',
  'Below knee amputation','BKA','Transmetatarsal amputation','TMA',
  'Ray amputation','Toe amputation','Finger amputation',
  'Debridement','Irrigation and debridement','I&D',
  'Bone graft','Bone cement','PMMA',
  'Spine instrumentation','Pedicle screws','Cage fusion',
  // Urology
  'TURP','Transurethral resection of prostate',
  'TURBT','Transurethral resection of bladder tumor',
  'Radical prostatectomy','Robotic prostatectomy',
  'Radical nephrectomy','Partial nephrectomy','Nephroureterectomy',
  'Radical cystectomy','Ileal conduit','Neobladder',
  'Ureteral stent','JJ stent','Double J stent','Ureteral reimplantation',
  'Ureteroscopy','URS','PCNL','Percutaneous nephrolithotomy',
  'ESWL','Extracorporeal shock wave lithotripsy',
  'Circumcision','Orchidectomy','Orchiectomy','Orchiopexy',
  'Hydrocelectomy','Varicocelectomy','Vasectomy',
  'Suprapubic catheter insertion','SPC insertion',
  // OB/GYN
  'Cesarean section','C-section','LSCS','Lower segment cesarean section',
  'Emergency cesarean','Elective cesarean',
  'Vaginal delivery','NVD','Normal vaginal delivery','SVD',
  'Instrumental delivery','Forceps delivery','Vacuum delivery',
  'Episiotomy','Perineal repair',
  'Hysterectomy','Total abdominal hysterectomy','TAH',
  'Total laparoscopic hysterectomy','TLH','Vaginal hysterectomy',
  'Myomectomy','Polypectomy','D&C','Dilation and curettage',
  'Hysteroscopy','Colposcopy','LEEP','Loop electrosurgical excision',
  'Salpingectomy','Salpingo-oophorectomy','BSO',
  'Bilateral salpingo-oophorectomy',
  'Ovarian cystectomy','Oophorectomy',
  'Tubal ligation','Essure',
  'Cervical cerclage','McDonald cerclage','Shirodkar cerclage',
  // Plastic surgery
  'Skin graft','Split-thickness skin graft','STSG',
  'Full-thickness skin graft','FTSG',
  'Flap','Local flap','Rotational flap','Advancement flap',
  'Free flap','Pedicled flap','Muscle flap',
  'Wound VAC','Negative pressure wound therapy','NPWT',
  'Scar revision','Keloid excision',
  'Burn excision','Burn debridement','Escharotomy',
  // ENT surgery
  'Tonsillectomy','Adenoidectomy','Adenotonsillectomy',
  'Septoplasty','Rhinoplasty','Septorhinoplasty',
  'FESS','Functional endoscopic sinus surgery',
  'Mastoidectomy','Tympanoplasty','Myringotomy','Tubes',
  'Parotidectomy','Submandibular gland excision',
  'Neck dissection','Modified radical neck dissection',
  'Laryngoscopy','Direct laryngoscopy','Microlaryngoscopy',
  'Laryngectomy','Total laryngectomy','Partial laryngectomy',
  // Ophthalmology
  'Cataract surgery','Phacoemulsification','IOL implantation',
  'Trabeculectomy','Glaucoma surgery','Tube shunt',
  'Vitrectomy','Pars plana vitrectomy','PPV',
  'Retinal detachment repair','Scleral buckle','Pneumatic retinopexy',
  'Corneal transplant','Keratoplasty','DSEK','DMEK',
  'Pterygium excision','Chalazion excision',
  'Enucleation','Evisceration','Exenteration',
  'Strabismus surgery','Dacryocystorhinostomy','DCR',
];

// ═══════════════════════════════════════════════════════════════════
// MICROBIOLOGY — organisms, resistance patterns
// ═══════════════════════════════════════════════════════════════════

export const MICROBIOLOGY = [
  // Gram positive cocci
  'Staphylococcus aureus','S. aureus','Staph aureus','MSSA','MRSA',
  'Coagulase-negative staphylococci','CoNS','S. epidermidis','S. saprophyticus',
  'Streptococcus pneumoniae','S. pneumoniae','Pneumococcus',
  'Streptococcus pyogenes','Group A Strep','GAS','S. pyogenes',
  'Streptococcus agalactiae','Group B Strep','GBS','S. agalactiae',
  'Viridans group streptococci','S. viridans','S. mitis','S. mutans',
  'Enterococcus faecalis','E. faecalis','Enterococcus faecium','E. faecium',
  'VRE','Vancomycin-resistant Enterococcus',
  // Gram positive rods
  'Listeria monocytogenes','Listeria','Corynebacterium','Diphtheroid',
  'Clostridium difficile','C. diff','C. difficile',
  'Clostridium perfringens','C. perfringens','Gas gangrene',
  'Clostridium tetani','Clostridium botulinum',
  'Bacillus cereus','Bacillus anthracis','Anthrax',
  'Nocardia','Actinomyces',
  // Gram negative cocci
  'Neisseria meningitidis','N. meningitidis','Meningococcus',
  'Neisseria gonorrhoeae','N. gonorrhoeae','Gonococcus',
  'Moraxella catarrhalis','M. catarrhalis',
  // Gram negative rods — Enterobacteriaceae
  'Escherichia coli','E. coli','ESBL E. coli',
  'Klebsiella pneumoniae','K. pneumoniae','ESBL Klebsiella','KPC',
  'Enterobacter cloacae','E. cloacae','Enterobacter aerogenes',
  'Proteus mirabilis','P. mirabilis','Proteus vulgaris',
  'Serratia marcescens','S. marcescens',
  'Citrobacter freundii','C. freundii','Citrobacter koseri',
  'Morganella morganii','M. morganii',
  'Salmonella','Salmonella typhi','Salmonella paratyphi',
  'Shigella','Shigella dysenteriae','Shigella sonnei',
  'Yersinia enterocolitica','Yersinia pestis',
  // Gram negative rods — non-fermenters
  'Pseudomonas aeruginosa','P. aeruginosa','Pseudomonas',
  'MDR Pseudomonas','XDR Pseudomonas',
  'Acinetobacter baumannii','A. baumannii','MDR Acinetobacter',
  'Stenotrophomonas maltophilia','S. maltophilia',
  'Burkholderia cepacia','B. cepacia',
  // Other gram negatives
  'Haemophilus influenzae','H. influenzae','H. flu',
  'Legionella pneumophila','Legionella','Legionnaires disease',
  'Bordetella pertussis','B. pertussis','Whooping cough',
  'Helicobacter pylori','H. pylori',
  'Campylobacter jejuni','Campylobacter',
  'Vibrio cholerae','Cholera','Vibrio vulnificus',
  'Brucella','Brucella melitensis','Brucella abortus',
  'Francisella tularensis','Tularemia',
  'Pasteurella multocida','P. multocida',
  'Bartonella henselae','Cat scratch disease',
  'Coxiella burnetii','Q fever',
  'Rickettsia','Rocky Mountain spotted fever','RMSF',
  'Treponema pallidum','Syphilis','RPR','VDRL','FTA-ABS',
  'Borrelia burgdorferi','Lyme disease',
  'Leptospira','Leptospirosis',
  'Mycobacterium tuberculosis','M. tuberculosis','MTB','TB',
  'Mycobacterium avium complex','MAC','MAI',
  'Mycobacterium abscessus','Mycobacterium kansasii',
  'Mycoplasma pneumoniae','M. pneumoniae','Atypical pneumonia',
  'Chlamydia pneumoniae','Chlamydophila','Chlamydia trachomatis',
  // Anaerobes
  'Bacteroides fragilis','B. fragilis',
  'Fusobacterium','Fusobacterium necrophorum','Lemierre syndrome',
  'Prevotella','Peptostreptococcus',
  // Fungi
  'Candida albicans','C. albicans','Candida glabrata','C. glabrata',
  'Candida auris','C. auris','Candida krusei','Candida parapsilosis',
  'Candida tropicalis','Candidemia','Invasive candidiasis',
  'Aspergillus fumigatus','A. fumigatus','Aspergillus niger',
  'Invasive aspergillosis','Aspergilloma','ABPA',
  'Cryptococcus neoformans','Cryptococcal meningitis',
  'Pneumocystis jirovecii','PCP','PJP',
  'Mucor','Rhizopus','Mucormycosis','Zygomycosis',
  'Histoplasma capsulatum','Histoplasmosis',
  'Coccidioides immitis','Coccidioidomycosis','Valley fever',
  'Blastomyces dermatitidis','Blastomycosis',
  'Sporothrix schenckii','Sporotrichosis',
  'Trichophyton','Microsporum','Epidermophyton','Dermatophyte',
  // Parasites
  'Plasmodium falciparum','P. falciparum','Plasmodium vivax','Malaria',
  'Toxoplasma gondii','Toxoplasmosis',
  'Giardia lamblia','Giardiasis',
  'Entamoeba histolytica','Amebic dysentery','Amebic liver abscess',
  'Cryptosporidium','Cryptosporidiosis',
  'Strongyloides stercoralis','Strongyloides hyperinfection',
  'Schistosoma','Schistosomiasis',
  'Echinococcus','Hydatid cyst',
  'Leishmania','Leishmaniasis','Visceral leishmaniasis','Kala-azar',
  // Viruses
  'Influenza A','Influenza B','H1N1','H3N2',
  'RSV','Respiratory syncytial virus',
  'Parainfluenza','Adenovirus','Rhinovirus','Enterovirus',
  'SARS-CoV-2','COVID-19','Omicron','Delta',
  'MERS-CoV','MERS','Middle East respiratory syndrome',
  'HIV-1','HIV-2','HIV viral load','CD4 count',
  'Hepatitis A','HAV','Hepatitis B','HBV','HBsAg','HBeAg','HBV DNA',
  'Hepatitis C','HCV','HCV RNA','HCV genotype',
  'Hepatitis D','HDV','Hepatitis E','HEV',
  'CMV','Cytomegalovirus','CMV IgG','CMV IgM','CMV PCR',
  'EBV','Epstein-Barr virus','EBV VCA','EBNA',
  'HSV-1','HSV-2','Herpes simplex','HSV PCR',
  'VZV','Varicella-zoster virus','Chickenpox','Shingles',
  'HHV-6','HHV-8','Kaposi sarcoma',
  'Parvovirus B19','Fifth disease',
  'Measles','Mumps','Rubella','MMR',
  'Dengue','Dengue hemorrhagic fever','Dengue shock syndrome',
  'Chikungunya','Zika','West Nile virus',
  'Rabies','Ebola','Marburg',
  'JC virus','BK virus','BK viremia',
  // Resistance patterns
  'MRSA','MSSA','VRSA','VISA',
  'VRE','VSE',
  'ESBL','Extended spectrum beta-lactamase',
  'AmpC','AmpC beta-lactamase',
  'CRE','Carbapenem-resistant Enterobacteriaceae',
  'CRPA','Carbapenem-resistant Pseudomonas aeruginosa',
  'CRAB','Carbapenem-resistant Acinetobacter baumannii',
  'KPC','Klebsiella pneumoniae carbapenemase',
  'NDM','New Delhi metallo-beta-lactamase',
  'OXA-48','VIM','IMP',
  'MDR','Multi-drug resistant','XDR','Extensively drug resistant',
  'PDR','Pan-drug resistant',
  'Sensitive','Susceptible','Resistant','Intermediate',
  'MIC','Minimum inhibitory concentration',
  'Zone of inhibition','Kirby-Bauer',
  'PCR positive','PCR negative','Culture positive','Culture negative',
  'No growth','Mixed flora','Normal flora','Contaminant',
];

// ═══════════════════════════════════════════════════════════════════
// PATHOLOGY & HISTOLOGY TERMS
// ═══════════════════════════════════════════════════════════════════

export const PATHOLOGY_TERMS = [
  'Biopsy','Core biopsy','Excisional biopsy','Incisional biopsy',
  'FNA','Fine needle aspiration','FNAB',
  'Frozen section','Permanent section',
  'H&E','Hematoxylin and eosin',
  'IHC','Immunohistochemistry',
  'Flow cytometry','Cytogenetics','FISH','Fluorescence in situ hybridization',
  'Histology','Cytology','Histopathology','Cytopathology',
  'Benign','Malignant','Premalignant','Dysplasia',
  'Mild dysplasia','Moderate dysplasia','Severe dysplasia',
  'Carcinoma in situ','CIS','Invasive carcinoma',
  'Adenocarcinoma','Squamous cell carcinoma','SCC',
  'Transitional cell carcinoma','TCC','Urothelial carcinoma',
  'Small cell carcinoma','Large cell carcinoma',
  'Well differentiated','Moderately differentiated','Poorly differentiated',
  'Undifferentiated','Anaplastic',
  'Grade 1','Grade 2','Grade 3','Grade 4',
  'Stage I','Stage II','Stage III','Stage IV',
  'Stage IA','Stage IB','Stage IIA','Stage IIB',
  'Stage IIIA','Stage IIIB','Stage IIIC',
  'Stage IVA','Stage IVB',
  'TNM staging','T1','T2','T3','T4','N0','N1','N2','N3','M0','M1',
  'Negative margins','Positive margins','Close margins',
  'R0 resection','R1 resection','R2 resection',
  'Lymphovascular invasion','LVI','Perineural invasion','PNI',
  'Sentinel node','Sentinel node positive','Sentinel node negative',
  'ER positive','ER negative','PR positive','PR negative',
  'HER2 positive','HER2 negative','Triple negative',
  'Ki-67','Proliferation index',
  'BRCA1','BRCA2','BRCA mutation',
  'Gleason score','Gleason 3+3','Gleason 3+4','Gleason 4+3',
  'Gleason 4+4','Gleason 4+5','Gleason 5+5',
  'PAP smear','ASCUS','LSIL','HSIL','ASC-H','AGC',
  'Inflammation','Acute inflammation','Chronic inflammation',
  'Granuloma','Granulomatous inflammation','Caseating granuloma',
  'Non-caseating granuloma',
  'Fibrosis','Necrosis','Coagulative necrosis','Liquefactive necrosis',
  'Fat necrosis','Caseous necrosis',
  'Thrombosis','Embolism','Infarction',
  'Hyperplasia','Hypertrophy','Atrophy','Metaplasia',
];

// ═══════════════════════════════════════════════════════════════════
// MEDICAL DEVICES & EQUIPMENT
// ═══════════════════════════════════════════════════════════════════

export const MEDICAL_DEVICES = [
  // Monitoring
  'Cardiac monitor','Telemetry','Telemetry monitor',
  'Pulse oximeter','SpO2 probe','End-tidal CO2','EtCO2','Capnography',
  'Arterial line','A-line transducer','CVP monitor',
  'Swan-Ganz catheter','PA catheter','Pulmonary artery catheter',
  'BIS monitor','Bispectral index',
  'ICP monitor','Intracranial pressure monitor',
  'EEG monitor','Continuous EEG',
  'Fetal monitor','CTG','Cardiotocograph',
  // Ventilation
  'Ventilator','Mechanical ventilator',
  'CPAP machine','BiPAP machine','HFNC','Optiflow',
  'Bag-valve mask','BVM','Ambu bag',
  'Nasal cannula','Face mask','Non-rebreather mask','NRB',
  'Venturi mask','Trach collar','T-piece',
  // Infusion
  'Infusion pump','Syringe driver','PCA pump',
  'IV pole','IV stand','Fluid warmer','Level 1','Belmont',
  'Blood warmer','Rapid infuser',
  // Renal
  'Dialysis machine','Hemodialysis machine',
  'CRRT machine','Prismaflex','Prismax','NxStage',
  'Peritoneal dialysis cycler','Baxter cycler',
  // Cardiac
  'Defibrillator','AED','Automated external defibrillator',
  'External pacemaker','Temporary pacemaker',
  'Permanent pacemaker','PPM','ICD','Implantable cardioverter defibrillator',
  'CRT','Cardiac resynchronization therapy','CRT-D','CRT-P',
  'IABP','Intra-aortic balloon pump',
  'Impella','ECMO circuit','ECMO cannula',
  // Tubes/Lines
  'Endotracheal tube','ETT','Tracheostomy tube','Trach tube',
  'Nasogastric tube','NGT','NG tube','OG tube',
  'Chest tube','Pigtail catheter','Blake drain',
  'JP drain','Jackson-Pratt drain','Penrose drain',
  'Foley catheter','Condom catheter','Texas catheter',
  'Suprapubic catheter','Nephrostomy tube',
  'Central line','Triple lumen catheter','Cordis',
  'PICC line','Midline catheter',
  'Peripherally inserted central catheter',
  'Hickman catheter','Broviac catheter','Groshong',
  'Port-a-Cath','Implanted port','Power port',
  'Arterial sheath','Introducer sheath',
  'Epidural catheter','Spinal needle','Tuohy needle',
  // Wound care
  'Wound VAC','Prevena','KCI VAC',
  'Wound dressing','Gauze','ABD pad','Tegaderm','Mepilex',
  'Aquacel','Duoderm','Hydrocolloid','Alginate',
  'Silver dressing','Honey dressing','Foam dressing',
  'Steri-strips','Dermabond','Skin glue',
  'Sutures','Staples','Surgical clips',
  'Compression wrap','ACE wrap','Unna boot',
  'TED stockings','SCDs','Sequential compression devices',
  // Orthopedic
  'Cast','Fiberglass cast','Plaster cast',
  'Splint','Sugar tong splint','Thumb spica','Short arm splint',
  'Long arm splint','Short leg splint','Long leg splint',
  'Walking boot','CAM boot','Sling','Collar and cuff',
  'Cervical collar','C-collar','Philadelphia collar','Miami J collar',
  'TLSO brace','LSO brace','Knee brace','Ankle brace',
  'Traction','Skin traction','Skeletal traction','Halo traction',
  'External fixator','Ilizarov','Taylor spatial frame',
  'CPM machine','Continuous passive motion',
  // Miscellaneous
  'Sequential compression devices','SCD',
  'Incentive spirometer','IS',
  'Glucometer','Blood glucose meter','CGM','Continuous glucose monitor',
  'Insulin pump','Omnipod','Tandem','Medtronic pump',
  'Hearing aid','Cochlear implant',
  'Prosthetic limb','Prosthesis',
  'Wheelchair','Electric wheelchair','Power wheelchair',
  'Hospital bed','Air mattress','Pressure-relieving mattress',
  'Bed alarm','Chair alarm','Fall mat',
  'Restraints','Soft restraints','Mittens',
  'Suction machine','Yankauer','Suction catheter',
  'Nebulizer','Spacer','MDI','Metered dose inhaler','DPI',
];

// ═══════════════════════════════════════════════════════════════════
// ALLERGY & ADVERSE DRUG REACTIONS
// ═══════════════════════════════════════════════════════════════════

export const ALLERGIES_ADR = [
  // Common allergens
  'Penicillin','Amoxicillin','Ampicillin','Augmentin',
  'Cephalosporin','Cefazolin','Ceftriaxone',
  'Sulfa','Sulfonamide','TMP-SMX','Bactrim',
  'Fluoroquinolone','Ciprofloxacin','Levofloxacin',
  'Vancomycin','Red man syndrome',
  'Metronidazole','Clindamycin',
  'Tetracycline','Doxycycline',
  'Macrolide','Azithromycin','Erythromycin',
  'Carbapenem','Meropenem','Imipenem',
  'NSAID','Ibuprofen','Naproxen','Diclofenac','Ketorolac','Aspirin',
  'Acetaminophen','Paracetamol',
  'Opioid','Morphine','Codeine','Tramadol','Fentanyl',
  'Contrast','Iodinated contrast','IV contrast','Gadolinium',
  'Latex','Rubber','Natural rubber latex',
  'Egg','Shellfish','Peanut','Tree nut','Soy','Wheat','Milk',
  'Bee sting','Wasp sting','Insect venom',
  'Adhesive tape','Tegaderm allergy','Chlorhexidine',
  'Heparin','HIT','Protamine',
  'Blood products','Transfusion reaction',
  'ACE inhibitor','Angioedema','ACEi angioedema',
  'Statin','Myopathy','Rhabdomyolysis',
  'Metformin','Lactic acidosis',
  'Allopurinol','DRESS syndrome',
  'Phenytoin','SJS','TEN',
  'Carbamazepine','Lamotrigine',
  // Reaction types
  'Anaphylaxis','Anaphylactic shock','Anaphylactoid',
  'Angioedema','Urticaria','Hives','Rash',
  'Maculopapular rash','Pruritus','Itching',
  'Bronchospasm','Wheezing','Laryngeal edema',
  'Hypotension','Tachycardia','Cardiovascular collapse',
  'Nausea','Vomiting','Diarrhea','Abdominal pain',
  'Serum sickness','Drug fever','Drug-induced lupus',
  'Interstitial nephritis','Drug-induced hepatitis',
  'Agranulocytosis','Thrombocytopenia','Hemolytic anemia',
  'QT prolongation','Torsades','Arrhythmia',
  'Serotonin syndrome','NMS','Neuroleptic malignant syndrome',
  'Malignant hyperthermia',
  'NKDA','No known drug allergies',
  'NKA','No known allergies',
  'NKFA','No known food allergies',
  'Allergy band','Allergy wristband','Red wristband',
  'Adverse reaction','ADR','Adverse drug reaction',
  'Side effect','Intolerance','Sensitivity',
  'Cross-reactivity','Cross-sensitivity',
  'Desensitization','Drug challenge','Graded challenge',
];

// ═══════════════════════════════════════════════════════════════════
// REHABILITATION & FUNCTIONAL ASSESSMENT
// ═══════════════════════════════════════════════════════════════════

export const REHABILITATION = [
  // PT terms
  'Physical therapy','PT','Physiotherapy',
  'Range of motion','ROM','Active ROM','AROM','Passive ROM','PROM',
  'Strength testing','Manual muscle testing','MMT',
  'Gait training','Gait analysis','Antalgic gait','Ataxic gait',
  'Trendelenburg gait','Steppage gait','Waddling gait',
  'Balance training','Proprioception','Coordination',
  'Transfer training','Bed mobility','Sit to stand',
  'Stair training','Community ambulation',
  'Assistive device','Cane','Quad cane','Walker','Rollator',
  'Crutches','Forearm crutches','Axillary crutches',
  'Wheelchair assessment','Power wheelchair evaluation',
  'Weight bearing status','WBAT','NWB','TDWB','PWB','FWB',
  'Weight bearing as tolerated',
  'Non-weight bearing','Touch down weight bearing',
  'Partial weight bearing','Full weight bearing',
  'Therapeutic exercise','Stretching','Strengthening',
  'Modalities','Ultrasound therapy','TENS','Electrical stimulation',
  'Heat therapy','Cold therapy','Cryotherapy',
  'Aquatic therapy','Hydrotherapy',
  // OT terms
  'Occupational therapy','OT',
  'ADL training','Activities of daily living',
  'IADL training','Instrumental activities of daily living',
  'Bathing','Dressing','Grooming','Toileting','Feeding',
  'Upper extremity function','Hand therapy','Grip strength',
  'Splinting','Orthosis','AFO','Ankle foot orthosis',
  'KAFO','Knee ankle foot orthosis',
  'Wrist splint','Resting hand splint','Dynamic splint',
  'Cognitive rehabilitation','Memory training','Attention training',
  'Visual perceptual training','Neglect training',
  'Home modification','Adaptive equipment',
  'Raised toilet seat','Shower chair','Grab bars',
  'Long-handled reacher','Sock aid','Button hook',
  // Speech therapy
  'Speech therapy','SLP','Speech-language pathology',
  'Swallow evaluation','Swallow study','VFSS','Videofluoroscopy',
  'FEES','Fiberoptic endoscopic evaluation of swallowing',
  'Dysphagia','Aspiration risk','Silent aspiration',
  'Diet modification','Pureed diet','Mechanically altered',
  'Nectar thick','Honey thick','Pudding thick',
  'Thin liquids','Thickened liquids',
  'Aphasia','Expressive aphasia','Receptive aphasia','Global aphasia',
  'Dysarthria','Apraxia of speech','Voice therapy',
  'Cognitive-linguistic therapy','Word finding','Naming',
  // Functional scores
  'FIM','Functional Independence Measure',
  'Barthel Index','Katz ADL','Lawton IADL',
  'Berg Balance Scale','BBS',
  'Timed Up and Go','TUG',
  '6-Minute Walk Test','6MWT',
  '10-Meter Walk Test','10MWT',
  'Modified Ashworth Scale','MAS',
  'Fugl-Meyer Assessment','FMA',
  'NIH Stroke Scale','NIHSS',
  'Modified Rankin Scale','mRS',
  'Glasgow Outcome Scale','GOS','GOS-E',
];

// ═══════════════════════════════════════════════════════════════════
// PEDIATRIC-SPECIFIC VOCABULARY
// ═══════════════════════════════════════════════════════════════════

export const PEDIATRIC_TERMS = [
  // Neonatal
  'Neonate','Newborn','Term','Preterm','Premature',
  'Gestational age','GA','Post-menstrual age','PMA',
  'Corrected age','Chronological age',
  'APGAR','APGAR score','APGAR 1 min','APGAR 5 min',
  'Birth weight','BW','VLBW','Very low birth weight',
  'ELBW','Extremely low birth weight','LBW','Low birth weight',
  'SGA','Small for gestational age','AGA','Appropriate for gestational age',
  'LGA','Large for gestational age',
  'RDS','Respiratory distress syndrome','Surfactant',
  'TTN','Transient tachypnea of newborn',
  'MAS','Meconium aspiration syndrome',
  'NEC','Necrotizing enterocolitis','Bell stage',
  'PDA','Patent ductus arteriosus','Indomethacin','Ibuprofen for PDA',
  'IVH','Intraventricular hemorrhage','Grade I','Grade II','Grade III','Grade IV',
  'PVL','Periventricular leukomalacia',
  'ROP','Retinopathy of prematurity','Zone I','Zone II','Zone III',
  'BPD','Bronchopulmonary dysplasia',
  'Neonatal jaundice','Phototherapy','Exchange transfusion',
  'Kernicterus','Bilirubin encephalopathy',
  'Neonatal sepsis','Early onset sepsis','Late onset sepsis',
  'TORCH','Toxoplasma','Rubella','CMV','HSV',
  'Congenital heart disease','CHD','VSD','ASD','PDA','TOF',
  'Tetralogy of Fallot','Coarctation of aorta','TGA',
  'Transposition of great arteries','HLHS','Hypoplastic left heart',
  // Pediatric general
  'Failure to thrive','FTT','Growth faltering',
  'Developmental delay','Global developmental delay','GDD',
  'Autism spectrum disorder','ASD','ADHD',
  'Cerebral palsy','CP','Spastic','Dyskinetic','Ataxic',
  'Febrile seizure','Simple febrile seizure','Complex febrile seizure',
  'Epilepsy','Infantile spasms','West syndrome','Lennox-Gastaut',
  'Kawasaki disease','MIS-C','Multisystem inflammatory syndrome',
  'Henoch-Schonlein purpura','HSP','IgA vasculitis',
  'Intussusception','Pyloric stenosis','Hirschsprung disease',
  'Nephrotic syndrome','Minimal change disease',
  'Acute glomerulonephritis','Post-streptococcal GN',
  'Croup','Viral croup','Spasmodic croup',
  'Bronchiolitis','RSV bronchiolitis',
  'Epiglottitis','Bacterial tracheitis',
  'Pertussis','Whooping cough','100-day cough',
  'Hand foot and mouth disease','HFMD',
  'Roseola','Exanthem subitum','HHV-6',
  'Fifth disease','Erythema infectiosum','Parvovirus B19',
  'Scarlet fever','Strep pharyngitis',
  'Impetigo','Periorbital cellulitis','Orbital cellulitis',
  // Pediatric milestones
  'Head control','Rolling','Sitting','Crawling','Walking',
  'First words','Sentences','Social smile','Stranger anxiety',
  'Immunization','Vaccination','DTaP','IPV','MMR','Hib',
  'PCV13','Rotavirus','Hepatitis B','Varicella vaccine',
  'Growth chart','Weight percentile','Height percentile',
  'Head circumference','HC percentile',
  'BMI percentile','Growth velocity',
];

// ═══════════════════════════════════════════════════════════════════
// PSYCHIATRY DEEP VOCABULARY
// ═══════════════════════════════════════════════════════════════════

export const PSYCHIATRY_TERMS = [
  'Major depressive disorder','MDD','Persistent depressive disorder',
  'Dysthymia','Treatment-resistant depression','TRD',
  'Bipolar I disorder','Bipolar II disorder','Cyclothymia',
  'Manic episode','Hypomanic episode','Mixed episode',
  'Schizophrenia','Schizoaffective disorder','Schizophreniform',
  'Brief psychotic disorder','Delusional disorder',
  'Generalized anxiety disorder','GAD',
  'Panic disorder','Panic attack','Agoraphobia',
  'Social anxiety disorder','SAD','Specific phobia',
  'Obsessive-compulsive disorder','OCD',
  'Post-traumatic stress disorder','PTSD','Acute stress disorder',
  'Adjustment disorder','Bereavement',
  'Somatic symptom disorder','Conversion disorder',
  'Illness anxiety disorder','Factitious disorder',
  'Anorexia nervosa','Bulimia nervosa','Binge eating disorder',
  'ARFID','Avoidant restrictive food intake disorder',
  'Borderline personality disorder','BPD',
  'Antisocial personality disorder','ASPD',
  'Narcissistic personality disorder','NPD',
  'Histrionic personality disorder',
  'Avoidant personality disorder',
  'Dependent personality disorder',
  'Schizoid personality disorder','Schizotypal personality disorder',
  'Intellectual disability','ID','Autism spectrum disorder','ASD',
  'ADHD','Attention deficit hyperactivity disorder',
  'Conduct disorder','Oppositional defiant disorder','ODD',
  'Insomnia','Sleep disorder','Circadian rhythm disorder',
  'Narcolepsy','Restless leg syndrome','RLS',
  'Alcohol use disorder','AUD','Opioid use disorder','OUD',
  'Stimulant use disorder','Cannabis use disorder',
  'Substance use disorder','SUD','Polysubstance use',
  'Delirium','Delirium tremens','DTs',
  'Dementia','Alzheimer disease','Vascular dementia',
  'Lewy body dementia','DLB','Frontotemporal dementia','FTD',
  'Suicidal ideation','SI','Suicidal intent','Suicidal plan',
  'Suicide attempt','SA','Self-harm','NSSI',
  'Non-suicidal self-injury',
  'Homicidal ideation','HI','Violent behavior',
  'Involuntary hold','Psychiatric hold','Section',
  'Capacity assessment','Competency evaluation',
  // Assessment tools
  'PHQ-9','PHQ-2','GAD-7','AUDIT-C','DAST-10',
  'Columbia Suicide Severity Rating Scale','C-SSRS',
  'Montreal Cognitive Assessment','MoCA',
  'Mini-Mental State Examination','MMSE',
  'Beck Depression Inventory','BDI',
  'Hamilton Rating Scale','HAM-D','HAM-A',
  'PANSS','Positive and Negative Syndrome Scale',
  'Yale-Brown Obsessive Compulsive Scale','Y-BOCS',
  'Clinical Global Impression','CGI',
  'Brief Psychiatric Rating Scale','BPRS',
  // Interventions
  'Electroconvulsive therapy','ECT',
  'Transcranial magnetic stimulation','TMS',
  'Cognitive behavioral therapy','CBT',
  'Dialectical behavior therapy','DBT',
  'Motivational interviewing','MI',
  'Group therapy','Family therapy','Psychoeducation',
  'Safety plan','Crisis plan','No-harm contract',
  'Involuntary admission','Voluntary admission',
  '1:1 observation','Close observation','Constant observation',
  'Seclusion','Restraint','Chemical restraint',
  'Rapid tranquilization','RT',
];

// ═══════════════════════════════════════════════════════════════════
// LOADER
// ═══════════════════════════════════════════════════════════════════

export function loadMegaSeedData(models) {
  const now = new Date().toISOString();

  const diagSources = [MICROBIOLOGY, PATHOLOGY_TERMS, PEDIATRIC_TERMS, PSYCHIATRY_TERMS, ALLERGIES_ADR, REHABILITATION];
  for (const source of diagSources) {
    for (const term of source) {
      const key = term.toLowerCase();
      if (key.length < 2) continue;
      if (!models.diagnoses[key]) {
        models.diagnoses[key] = { count: 1, entity: 'CLINICAL_TERM', lastSeen: now, confidence: 0.65, seeded: true };
      }
    }
  }

  for (const proc of SURGICAL_PROCEDURES) {
    const key = proc.toLowerCase();
    if (!models.diagnoses[key]) {
      models.diagnoses[key] = { count: 1, entity: 'PROCEDURE', lastSeen: now, confidence: 0.68, seeded: true };
    }
  }

  for (const device of MEDICAL_DEVICES) {
    const key = device.toLowerCase();
    if (!models.diagnoses[key]) {
      models.diagnoses[key] = { count: 1, entity: 'DEVICE', lastSeen: now, confidence: 0.60, seeded: true };
    }
  }

  models.megaSeeded = true;
  return models;
}
