// OCR Seed — Nursing Documentation Intelligence
// Nursing assessments, care plans, NANDA diagnoses, NIC/NOC,
// charting patterns, flowsheet terms, wound staging, fall scales,
// pain scales, sedation scales, nursing handover, patient education

export const NANDA_DIAGNOSES = [
  // Activity/Rest
  'Activity intolerance','Decreased cardiac output','Fatigue',
  'Impaired physical mobility','Impaired bed mobility','Impaired walking',
  'Impaired wheelchair mobility','Impaired transfer ability',
  'Sedentary lifestyle','Sleep deprivation','Insomnia',
  'Disturbed sleep pattern','Readiness for enhanced sleep',
  // Comfort
  'Acute pain','Chronic pain','Labor pain','Nausea',
  'Impaired comfort','Social isolation',
  // Elimination
  'Bowel incontinence','Constipation','Perceived constipation',
  'Diarrhea','Dysfunctional gastrointestinal motility',
  'Impaired urinary elimination','Urinary incontinence',
  'Stress urinary incontinence','Urge urinary incontinence',
  'Functional urinary incontinence','Overflow urinary incontinence',
  'Urinary retention','Impaired gas exchange',
  // Fluid/Electrolyte
  'Deficient fluid volume','Excess fluid volume',
  'Risk for deficient fluid volume','Risk for electrolyte imbalance',
  'Risk for imbalanced fluid volume',
  // Growth/Development
  'Delayed growth and development','Risk for delayed development',
  'Adult failure to thrive',
  // Nutrition
  'Imbalanced nutrition: less than body requirements',
  'Imbalanced nutrition: more than body requirements',
  'Risk for imbalanced nutrition','Impaired swallowing',
  'Ineffective infant feeding pattern','Readiness for enhanced nutrition',
  'Risk for aspiration','Risk for unstable blood glucose',
  // Oxygenation
  'Ineffective airway clearance','Ineffective breathing pattern',
  'Impaired gas exchange','Impaired spontaneous ventilation',
  'Dysfunctional ventilatory weaning response',
  'Risk for suffocation',
  // Safety/Protection
  'Risk for falls','Risk for injury','Risk for trauma',
  'Risk for perioperative positioning injury',
  'Impaired skin integrity','Risk for impaired skin integrity',
  'Impaired tissue integrity','Risk for impaired tissue integrity',
  'Ineffective protection','Risk for infection',
  'Risk for surgical site infection',
  'Contamination','Risk for contamination',
  'Risk for bleeding','Risk for shock',
  'Risk for peripheral neurovascular dysfunction',
  'Risk for pressure ulcer','Pressure injury',
  'Impaired oral mucous membrane','Impaired dentition',
  'Risk for aspiration','Risk for sudden infant death',
  'Ineffective thermoregulation','Hypothermia','Hyperthermia',
  'Risk for imbalanced body temperature',
  'Latex allergy response','Risk for latex allergy',
  // Self-Care
  'Bathing self-care deficit','Dressing self-care deficit',
  'Feeding self-care deficit','Toileting self-care deficit',
  'Self-neglect','Readiness for enhanced self-care',
  // Sensory/Perception
  'Disturbed sensory perception','Unilateral neglect',
  'Disturbed body image','Chronic low self-esteem',
  'Situational low self-esteem','Powerlessness','Hopelessness',
  // Cognition
  'Acute confusion','Chronic confusion','Impaired memory',
  'Deficient knowledge','Readiness for enhanced knowledge',
  'Impaired verbal communication','Readiness for enhanced communication',
  'Wandering',
  // Coping
  'Ineffective coping','Compromised family coping',
  'Defensive coping','Ineffective denial',
  'Anxiety','Death anxiety','Fear','Grieving',
  'Complicated grieving','Risk for complicated grieving',
  'Post-trauma syndrome','Rape-trauma syndrome',
  'Risk for self-directed violence','Risk for other-directed violence',
  'Self-mutilation','Risk for self-mutilation',
  'Risk for suicide','Moral distress',
  // Perfusion
  'Ineffective tissue perfusion','Risk for decreased cardiac tissue perfusion',
  'Risk for ineffective cerebral tissue perfusion',
  'Risk for ineffective renal perfusion',
  'Risk for ineffective GI perfusion',
  'Risk for ineffective peripheral tissue perfusion',
  'Decreased intracranial adaptive capacity',
  'Risk for unstable blood pressure',
];

export const NURSING_INTERVENTIONS_NIC = [
  // Physiological Basic
  'Acid-base management','Airway management','Airway suctioning',
  'Aspiration precautions','Bathing','Bed rest care',
  'Bleeding precautions','Bleeding reduction',
  'Blood products administration','Body mechanics promotion',
  'Bowel management','Cardiac care','Cast care',
  'Cerebral edema management','Chest physiotherapy',
  'Circulatory care','Cough enhancement',
  'Electrolyte management','Elimination management',
  'Emergency care','Endotracheal extubation',
  'Energy management','Exercise promotion',
  'Fall prevention','Feeding','Fever treatment',
  'First aid','Fluid management','Fluid monitoring',
  'Fluid resuscitation','Gastrointestinal intubation',
  'Heat/cold application','Hemodynamic regulation',
  'Hemorrhage control','Hyperglycemia management',
  'Hypoglycemia management','Hypothermia treatment',
  'Infection control','Infection protection',
  'Intracranial pressure monitoring','Intravenous therapy',
  'Invasive hemodynamic monitoring',
  'Medication administration','Medication management',
  'Neurological monitoring','Nutrition management',
  'Oral health maintenance','Ostomy care',
  'Oxygen therapy','Pain management',
  'Peripheral sensation management',
  'Peritoneal dialysis therapy','Phlebotomy',
  'Positioning','Postanesthesia care',
  'Postmortem care','Pressure ulcer prevention',
  'Respiratory monitoring','Seizure management',
  'Seizure precautions','Self-care assistance',
  'Shock management','Shock prevention',
  'Skin care','Skin surveillance',
  'Specimen management','Splinting',
  'Suction airway','Surveillance',
  'Temperature regulation','Total parenteral nutrition',
  'Traction care','Tube care',
  'Urinary catheterization','Urinary elimination management',
  'Ventilation assistance','Vital signs monitoring',
  'Vomiting management','Weight management',
  'Wound care','Wound irrigation',
  // Physiological Complex
  'Acid-base monitoring','Artificial airway management',
  'Autotransfusion','Blood products administration',
  'Central venous access device management',
  'Code management','Defibrillator management',
  'Dialysis access maintenance','Electrolyte monitoring',
  'Hemofiltration therapy','Hypervolemia management',
  'Hypovolemia management','Induced hypothermia',
  'Intracranial pressure monitoring','Invasive hemodynamic monitoring',
  'Mechanical ventilation management','Mechanical ventilatory weaning',
  'Organ procurement','Pacemaker management',
  'Peritoneal dialysis therapy','Radiation therapy management',
  'Shock management cardiac','Shock management vasogenic',
  'Shock management volume','Thrombolytic therapy management',
  // Behavioral
  'Anger control assistance','Anxiety reduction',
  'Behavior management','Calming technique',
  'Cognitive stimulation','Coping enhancement',
  'Counseling','Crisis intervention',
  'Delirium management','Delusion management',
  'Dementia management','Distraction',
  'Emotional support','Environmental management',
  'Grief work facilitation','Guilt work facilitation',
  'Hallucination management','Impulse control training',
  'Limit setting','Milieu therapy',
  'Mood management','Music therapy',
  'Patient contracting','Reality orientation',
  'Relaxation therapy','Reminiscence therapy',
  'Restraint use','Seclusion',
  'Security enhancement','Self-awareness enhancement',
  'Self-esteem enhancement','Sleep enhancement',
  'Substance use prevention','Substance use treatment',
  'Suicide prevention','Support group',
  'Therapeutic play','Validation therapy',
  // Safety
  'Allergy management','Anaphylaxis management',
  'Area restriction','Bleeding precautions',
  'Environmental management safety',
  'Fall prevention','Fire-setting precautions',
  'Infection control','Latex precautions',
  'Physical restraint','Radiation therapy management',
  'Seizure precautions','Suicide prevention',
  'Surgical precautions','Vehicle safety promotion',
  'Wandering prevention',
];

export const NURSING_FLOWSHEET_TERMS = [
  // Neuro checks
  'LOC','Level of consciousness','Alert','Drowsy','Obtunded','Comatose',
  'Oriented x3','Oriented x4','Oriented to person','Oriented to place',
  'Oriented to time','Oriented to situation','Disoriented',
  'PERRL','PERRLA','Pupils equal','Pupils unequal','Anisocoria',
  'Pupil size','2mm','3mm','4mm','5mm','6mm','7mm','8mm',
  'Brisk','Sluggish','Non-reactive','Fixed','Fixed and dilated',
  'Right pupil','Left pupil','Both pupils',
  'Moves all extremities','MAE','MAE x4',
  'Right arm','Left arm','Right leg','Left leg',
  'Strength 5/5','Strength 4/5','Strength 3/5','Strength 2/5','Strength 1/5','Strength 0/5',
  'Flaccid','Spastic','Rigid','Clonus',
  'Babinski positive','Babinski negative','Plantar flexion','Dorsiflexion',
  // Cardiac
  'Sinus rhythm','Sinus tachycardia','Sinus bradycardia',
  'Atrial fibrillation','Atrial flutter','SVT','VT','PVCs','PACs',
  'Paced rhythm','AV paced','Ventricular paced',
  'Heart sounds','S1','S2','S3','S4','Murmur','No murmur',
  'JVD','JVP','Elevated JVP','Flat JVP',
  'Capillary refill','Cap refill <2 sec','Cap refill >3 sec',
  'Radial pulse','Pedal pulse','Dorsalis pedis','Posterior tibial',
  'Pulse strong','Pulse weak','Pulse thready','Pulse absent',
  'Skin warm','Skin cool','Skin mottled','Skin diaphoretic',
  'Color pink','Color pale','Color cyanotic','Color flushed','Color jaundiced',
  // Respiratory
  'Breath sounds clear','Breath sounds diminished','Breath sounds absent',
  'Crackles','Rales','Rhonchi','Wheezes','Stridor',
  'Accessory muscle use','Nasal flaring','Retractions',
  'Chest expansion equal','Chest expansion unequal',
  'Cough strong','Cough weak','Cough absent','Cough productive',
  'Sputum clear','Sputum white','Sputum yellow','Sputum green','Sputum bloody',
  'Sputum amount small','Sputum amount moderate','Sputum amount large',
  'Ventilator mode','SIMV','AC','PS','CPAP','FiO2','PEEP','TV','RR set',
  'Peak pressure','Plateau pressure','Minute ventilation',
  // GI
  'Abdomen soft','Abdomen firm','Abdomen distended','Abdomen rigid',
  'Bowel sounds present','Bowel sounds hypoactive','Bowel sounds hyperactive','Bowel sounds absent',
  'NG tube draining','NG output','Residual','Residual volume',
  'Tube feeding running','Tube feeding held','Tube feeding rate',
  'Diet tolerated','Diet not tolerated','Poor PO intake','Good PO intake',
  'Nausea present','Nausea absent','Vomiting present','Vomiting absent',
  'Last BM','BM today','No BM','Constipated',
  'Stool brown','Stool loose','Stool formed','Stool watery',
  'Stool black','Stool bloody','Stool guaiac positive','Stool guaiac negative',
  'Ostomy functioning','Stoma pink','Stoma dusky',
  // GU
  'Foley patent','Foley draining','Urine clear','Urine cloudy','Urine amber',
  'Urine dark','Urine bloody','Urine concentrated',
  'UOP adequate','UOP decreased','UOP absent',
  'Voiding spontaneously','Unable to void','Bladder scan',
  'Post-void residual','PVR','Intermittent catheterization',
  // Skin/Wound
  'Skin intact','Skin breakdown','Skin tear','Skin reddened',
  'Blanchable','Non-blanchable','Stage I','Stage II','Stage III','Stage IV',
  'DTPI','Deep tissue pressure injury','Unstageable',
  'Wound bed red','Wound bed pink','Wound bed yellow','Wound bed black',
  'Granulation tissue','Slough','Eschar','Necrotic tissue',
  'Wound edges approximated','Wound edges open','Undermining','Tunneling',
  'Wound length','Wound width','Wound depth',
  'Wound drainage serous','Wound drainage serosanguinous','Wound drainage sanguinous',
  'Wound drainage purulent','Wound drainage amount minimal','Wound drainage amount moderate',
  'Wound odor none','Wound odor present','Wound odor foul',
  'Periwound skin intact','Periwound skin macerated','Periwound erythema',
  'Dressing clean dry intact','Dressing saturated','Dressing changed',
  'Wound VAC functioning','Wound VAC pressure','Wound VAC canister',
  'Braden score','Norton score','Waterlow score',
  'Turn schedule','Repositioned','Turn Q2H','Offloading',
  'Pressure redistribution','Heel float','Heel elevation',
  // IV/Lines
  'PIV patent','PIV flushed','PIV site CDI','PIV discontinued',
  'PIV site redness','PIV infiltrated','PIV occluded',
  'Central line site CDI','Central line dressing changed',
  'Central line flushed','Central line day',
  'PICC site CDI','PICC flushed','PICC dressing changed',
  'Arterial line patent','Arterial line zeroed','A-line waveform',
  'Site clean dry intact','CDI','No redness','No swelling','No drainage',
  'Line day #1','Line day #2','Line day #3','Line day #4','Line day #5',
  // Safety
  'Fall risk assessment','High fall risk','Low fall risk','Moderate fall risk',
  'Morse fall scale','Morse score',
  'Bed in low position','Side rails up','Call light within reach',
  'Non-slip socks','Gait belt','Bed alarm on','Chair alarm on',
  'Restraints applied','Restraints released','Restraint assessment',
  'Neurovascular checks','CMS check','Color motion sensation',
  'Precautions in place','Isolation in place','PPE donned',
  'Hand hygiene performed','Contact precautions','Droplet precautions',
  'Airborne precautions','N95 required',
  // Education
  'Patient education provided','Verbalized understanding',
  'Return demonstration','Teach-back method',
  'Discharge teaching','Medication teaching','Diet teaching',
  'Activity restrictions reviewed','Follow-up appointments reviewed',
  'Signs and symptoms to report','When to call doctor',
  'When to go to ER','Written instructions provided',
  'Interpreter used','Family present for teaching',
  'Barriers to learning','Low health literacy',
  'Visual impairment','Hearing impairment','Language barrier',
  'Cognitive impairment','Willing to learn','Motivated',
  'Anxious','Distracted','Not receptive',
];

export const NURSING_SHIFT_REPORT = [
  // Handover structure
  'Report given to','Report received from',
  'Oncoming nurse','Off-going nurse',
  'Charge nurse','Resource nurse',
  'Primary nurse','Assigned nurse',
  'Day shift','Night shift','Evening shift',
  '0700','0730','1500','1530','1900','1930','2300','2330',
  '7-3','3-11','11-7','12-hour shift','8-hour shift',
  // Content
  'Significant events','Overnight events','Nothing significant',
  'No events overnight','Slept well','Restless night',
  'Pain controlled','Pain uncontrolled','Required PRN',
  'Febrile overnight','Afebrile','Temp spike',
  'Blood sugar stable','Blood sugar elevated','Blood sugar low',
  'Insulin coverage given','Sliding scale','FSBS Q6H',
  'IV fluids running','IV fluids completed','Hep lock',
  'Antibiotics due','Next dose due','Last dose given',
  'Labs pending','Labs resulted','Critical lab',
  'MD notified','MD aware','Waiting for MD',
  'New orders','Order clarification needed',
  'Procedure scheduled','NPO for procedure','Consent obtained',
  'Family visited','Family updated','Family conference pending',
  'Social work consulted','Case management involved',
  'PT/OT evaluated','PT cleared','OT recommendations',
  'Discharge planning','Tentative discharge','Barrier to discharge',
  'Code status confirmed','DNR confirmed','Full code',
  'Safety sitter','1:1','Close observation','Elopement risk',
  'Fall risk','High fall risk','Fall precautions in place',
  'Skin assessment done','New skin breakdown','Wound improving',
  'Restraint assessment','Restraints continued','Restraints discontinued',
  'Blood transfusion given','Transfusion reaction','No reaction',
  'Foley care done','Foley Day #','Consider removal',
  'Central line care done','Line Day #','Consider removal',
  'Diet changed','Tolerating diet','Poor intake',
  'Bowel protocol started','Last BM','Needs bowel care',
  'Emotional support provided','Coping well','Tearful','Anxious',
];

export function loadNursingSeedData(models) {
  const now = new Date().toISOString();
  const allTerms = [
    ...NANDA_DIAGNOSES,
    ...NURSING_INTERVENTIONS_NIC,
    ...NURSING_FLOWSHEET_TERMS,
    ...NURSING_SHIFT_REPORT,
  ];
  for (const term of allTerms) {
    const key = term.toLowerCase();
    if (key.length < 2) continue;
    if (!models.diagnoses[key]) {
      models.diagnoses[key] = { count: 1, entity: 'NURSING', lastSeen: now, confidence: 0.60, seeded: true };
    }
  }
  models.nursingSeeded = true;
  return models;
}
